### ISSUE TITLE
Additional Info in Stats

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#10]
I think we are going to need some info on the  local change history reported in ]stats.

Perhaps something like:

`Change History: 35mb in 250 files.`

This might even be useful as an additional column in the result of ]projects, or spilling into the session when you open the project.

**Comment by norberturkiewicz** [comment]
Can this information be presented in for ways?

1) The default, two column matrix of name value pairs for display consumption. 

 ]ACRE.Stats

2) Namespace with variables containing the same data.  We used to to use GetProerty to get product specic information but it would be easier to have one command that returns everything. 

]ns<-ACRE.Stats -ns

**Comment by PhilLast** [comment]
```
      ]stats acre
.--------------------------------------.
| When opened:     2018-04-26 21:00:26 |
| Time to load:                     1s |
|                                      |
| Variables                          4 |
| Functions                        362 |
| Operators                         81 |
| Scripts                            2 |
| Classes                            4 |
| Interfaces                         0 |
|                                      |
| Total items:     453 in 9 namespaces |
| Change History:    703kB in 43 files |
'--------------------------------------'
```
Done
