### ISSUE TITLE
Should load dependencies be initiated before the project?

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#100]
I'm having an issue opening a project where the dependent class or namespace has not yet been loaded and the interpreter is throwing errors.  This will go away with late binding in 17.0 but it opens up the issue of load order.

**Comment by PhilLast** [comment]
For multiple projects, if we have
*.../A/acreconfig.txt* containing:
`load←'B'`
*.../B/acreconfig.txt* containing:
`load←'C'`
And we do `]openproject A` what currently happens, or is supposed to happen, is that loading of `A` is deferred until `B` has loaded while loading of `B` is deferred until `C` is loaded.

Within a project all scripted spaces are fixed. The classes are then put into a loop where all are tried. Any failing to fix are then tried again until either none are left to fix or none are fixed within a particular iteration.

Does this help?
