### ISSUE TITLE
acre should pass on the "Fix" event 

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#101]
In a mixed environment one might well have to manage proejcts with acre but also scripts with SALT.

acre wouldbe a better citizen of the Dyalog APL world if it wouldn't not swallow the "Fix" event even if it worked out that it won't/can't take care of a particular object. Instead it should pass the event on so that SALT can take care of it if it wants to.

This will certainly be a requirement by Dyalog anyway.

**Comment by PhilLast** [comment]
Even better would be for Link to be configurable in such a way that acre and any other similar tool could use it to do what ⎕SE.SALT.EditorFix and ⎕SE.acre.EditFix currently do in their own way. One would assume that SALT will be amended to use Link if the latter doesn't make it redundant.

Dyalog would then be in a position to rewrite the Fix event without exposing it and without having to worry that changes to it would break other people's existing code. Which latter concern it seems they were lacking anyway.

As to acre's "swallowing" the event. As things stand it's either acre or SALT. There appear to be no hooks in SALT to allow the event to be passed on if ⎕SE.SALT.EditorFix cannot handle it.

**Comment by aplteam** [comment]
> There appear to be no hooks in SALT to allow the event to be passed on if ⎕SE.SALT.EditorFix cannot handle it.

It doesn't have to: it's fine for acre being the principle handler (right now that is) and pass it on or rather call the SALT handler with the approriate arguments.

That could be done back until version 15.0 while Link is only of concern with 17.0 onwards.

**Comment by PhilLast** [comment]
I don't see how this would be possible.

Acre could call ⎕SE.SALT.EditorFix directly with the same argument but acre currently ignores the AfterFix event that couldn't in any case be handed over without disabling acre for the rest of the session.

**Comment by PhilLast** [comment]
Have this working.

Once acre is started exiting the editor issues the __Fix__ event that calls acre's _editFix_ function that checks to see if the item is in a tracked project.
If so acre temporarily stores the old value and we await the __AfterFix__ event.
Else _editFix_ calls the equivalent _SALTUtils_ function that does what it does.
If neither acre nor _SALTUtils_ has cancelled the __Fix__ then Dyalog fixes the item assuming it has been changed and the __AfterFix__ event is triggered and calls acre again. 
If acre handled the first call the old value is retrieved, compared to the new and if different acre saves the item to _APLSource/_ and possibly to _.acre/changes/_.
Else acre calls the _SALTUtils_ function again and it does what it does.

Seems to work fine. The one drawback is that acre can no longer message its inability to handle an item unless it does so whether or not the item is changed and whether or not SALT handled it. 
My preference is for the former - no message.

I can push it forward if no-one objects.

Technical point - whatever the new seventh item in the argument to the callback - which acre ignores - it _is_ being passed on to SALT.
