### ISSUE TITLE
casecode=off

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#102]
Having finally got around to doing something about it I think the `casecode=off` option would be better as a *modifier* rather than as an item in the argument. Currently we have
`]createproject folder/ #.space` 
or
`]createproject folder/ #.space off` 
or redundantly
`]createproject folder/ #.space on`
where the meaning of each item in the argument is implicit.
I propose we have
`]createproject folder/ #.space` 
or
`]createproject folder/ #.space -casecode=off` 
or redundantly
`]createproject folder/ #.space -casecode=on` 
This option should still be available only in `]createproject` requiring a deliberate (and permanent) edit of the config file to change it after creation.

As the casecode option in the argument or the config file has been honoured for only the past week I assume this will break no-one's code and will make the change unless there is objection today.

**Comment by e9gille** [comment]
I agree, modifier is better.

**Comment by PhilLast** [comment]
Implemented
