### ISSUE TITLE
.function vs .aplf &c.

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#104]
The latest development build of acre is now able to read and potentially to write the *enhanced standard Dyalog* filetypes *in addition* to its own *native* types.
```
   acre        Dyalog
    .array       .apla
    .function    .aplf
    .operator    .aplo
    .script      .apln
    .class       .aplc
    .interface   .apli
    .charstring  .apls
    .charlist    .apll
    .charmat     .aplm
```

It won't write them until we decide a method to indicate which set a project is using.

We *could* make a decision that following a particular release, `CreateProject` will set an internal flag to force the standard *on any new project*.

We *could* make such a flag public as a new configuration setting.

We *could* create any new sourcefile in a project as standard if any standard type exists in the source-tree but continue with the native types if not.

I do not envision turning off the ability to read the native types until some time after the renaming of files in response to the guidelines [set out in the wiki](/the-carlisle-group/Acre-Desktop/wiki/Item-Names-and-File-Names#resolving-inconsistent-names-and-case-codes) is complete. I'm working on it.

**Comment by PhilLast** [comment]
The filetypes are still unchanged from their originals.
The current Dyalog-preferred alternatives are:

acre | Dyalog
---- | ------
 .aplf   |     .function   
 .aplo   |     .operator   
 .apln    |    .script     
 .aplc     |   .class      
 .apli     |   .interface  

_.array, .charstring, .charmat_ & _.charlist_ remaining the same.

Changing the bit in acre's _nameClass_ function will cause all _.function, .operator, .script, .class_ & _.interface_ files to be renamed the next time each project is opened. This will take a few seconds for a large project such as CAS and will probably entail rather a lot of messages unless the `]openproject` command is issued with the `-m=off` option.

When?

**Comment by e9gille** [comment]
I'd like that in before the user meeting if possible.

**Comment by PhilLast** [comment]
commit "New filetypes" @ 2018-10-25 22.30 UTC as version 4.8.1.036

@e9gille would this follow protocol better as a pre-release?

**Comment by PhilLast** [comment]
Doesn't really matter now but I've just switched the headings in the table above to put them above the correct columns.

**Comment by e9gille** [comment]
Ohh, thank you very much!

>would this follow protocol better as a pre-release?

I don't know. Arguably you could bump the minor version as it technically isn't a bug fix, but at the same time it isn't a breaking change (is it?). As I understand it, if I use the new version on a project, some files change extensions. Going back to a previous version of Acre would rename them back again, right?

**Comment by PhilLast** [comment]
Yes indeed!
