### ISSUE TITLE
fPath incorrect on unix for paths with repeated ..

### ISSUE THREAD

**Issue by e9gille** [the-carlisle-group/Acre-Desktop#105]
See

https://github.com/the-carlisle-group/Acre-Desktop/blob/145d1a993a81d6b94e560d9080a794b83c9f6704/APLSource/_code-0/fPath-2.function#L4

Current implementation doesn't expect a sequence of `..` in path:
```
      fPath '/a/b/c/../../d/'
/a/b/d/
```
Expected
```
      fPath '/a/b/c/../../d/'
/a/d/
```

**Comment by PhilLast** [comment]
Thanks Gil.
`     ⊃(⊣,'/',⊢)/{⍵/⍨(⊢⍱¯1⌽⊢)0 1⍷⍵∊⊂'..'}⍣≡'/'sep r` seems to work. I'm sure there must be a nattier boolean operation without the iteration but it'll do for now. About to commit and push changes that rename sourcefiles producing items with different name or type. So this can come alongside. Of course you can make your own local change for now.

**Comment by e9gille** [comment]
If I read it right the above removes pairs of something followed by `..` until no more are found. I can spot one edge condition that it doesn't catch, namely when going beyond the root. It should be:

```
      fPath '/root/../../'
/
      fPath 'root/../../'
../
```

I think this would solve that issue:
`⊃(⊣,'/',⊢)/{⍵/⍨(⊢⍱¯1⌽⊢)2 0⍷'..' ''⍳⍵}⍣≡'/'sep r`

**Comment by PhilLast** [comment]
I must admit I never considered the possibility. So far as I was aware that operation in _fPath_ was only catching constructions put there by acre in which case going beyond the root _should_ be out of the question.

**Comment by e9gille** [comment]
Well, there is nothing to stop a user from providing a path like that on open or create, but I can see why you would question someone doing that. In my case it happened in my dependency loader where the path is constructed automatically and sometimes has to inspect parent/sibling folders.

I can of course change my calling function to construct a path by cutting back instead of appending `..\`.

**Comment by PhilLast** [comment]
I'll put in your change anyway. My comment above was only an excuse for not having taken it into account. Thanks.

**Comment by PhilLast** [comment]
While testing I discovered a possible DOMAIN error at `(⊣,'/',⊢)/` in both algorithms. It's not currently possible as all calls to `fPath` ensure a trailing '/' but that reduction is in all cases equivalent to the quicker but uglier `1↓⊃,/'/',¨` now replaced in both. 

Having no 'nix I have to take your word for it that your "should be"s above are correct because so far as I know in windows `1∘⎕NPARTS` always returns a path starting in `[drive]:/` where both algorithms return the same.

**Comment by e9gille** [comment]
> Having no 'nix I have to take your word for it that your "should be"s above are correct because so far as I know in windows 1∘⎕NPARTS always returns a path starting in [drive]:/ where both algorithms return the same.

Sorry, that's my bad. I overlooked the `1 ⎕NPARTS`. With that you would similarly get a path starting with `/` in unix (making my suggested fix redundant).

Funny enough I also looked at the `⊃(⊣,'/',⊢)/` and compared it to the `1↓⊃,/'/',¨`. I thought you may get in trouble with the former, but could only see that happening if it was applied to an empty element and as you say, that is not expected to ever happen, so I kept my mouth shut (for once).

**Comment by PhilLast** [comment]
In windows `1∘⎕nparts` removes superfluous "`/..`" so without further intervention we get
```
   ⊃,/1 ⎕NPARTS 'a:/b/'
a:/b/
   ⊃,/1 ⎕NPARTS 'a:/b/../'
a:/
   ⊃,/1 ⎕NPARTS 'a:/b/../../'
a:/
   ⊃,/1 ⎕NPARTS 'a:/b/../../../'
a:/
```
In a 'nix system it what _should_ these results be:
```
   fPath'/a/b/'
/a/b/
   fPath'/a/b/../'
/a/
   fPath'/a/b/../../'
/
   fPath'/a/b/../../../'
/../
```
Should the last one be "`/`" also?

**Comment by e9gille** [comment]
> Should the last one be "/" also?

Yes, it should.

In theory, what `1 ⎕NPARTS` does is the most correct way of handling this, although I don't know that it would make much of a difference when paths are used from Acre. In unix, if you have a link:
```
/root/link -> /root/to/some/other/place
cd /root/link/../../..
/
but
cd -P /root/link/../../..
/root/to
```

**Comment by PhilLast** [comment]
Can anyone say if this works now?
