### ISSUE TITLE
If project folder descendant of a folder with a leading dot, no source is read in when opened

### ISSUE THREAD

**Issue by e9gille** [the-carlisle-group/Acre-Desktop#106]
See

https://github.com/the-carlisle-group/Acre-Desktop/blob/145d1a993a81d6b94e560d9080a794b83c9f6704/APLSource/_code-0/getSource-8.function#L6

For example:
```
]acre.openproject /Users/gil/.apl/project
```
Results in no source found.

**Comment by PhilLast** [comment]
Looked at this momentarily last evening. Have you changed it? Never mind. Took me a while to comprehend the problem.
Your suggestion I saw in the email looks good.
`path date/⍨←⊂~∨/'/.'⍷(≢src)↓⍤1↑path`

I guess you've tried it like that and it works?

Have to go out now. Back to this for a while this pm.

**Comment by e9gille** [comment]
Yes, I tested it and it solved my problem. I'm still unsure about the intention, the comment unfortunately only mirrors the APL expression (ignore all /.*/) so I wasn't sure why it was done.

**Comment by PhilLast** [comment]
Your examples are correct but I wonder if they're realistic. In practice I think most users would tend to use their own substitute for "APLSource" giving it a project specific name. My copy of CAS7 (not up-to-date) has about 150 folders in APLSource and none called "CAS" which is the projectspace name specified in the config file. Likewise FlipDB has about 50 folders and 30 classes in APLSource and no folder "flipdb".

The algorithm for discovering the common folder stops at the project itself. Were your NS1 NS2 scenario to occur, the first time the project were opened would show a new redundancy in the design. Projects are expected, 'though not required, to be relocatable. In all likelihood nothing would go wrong.

If acre acquires the necessity to import and possibly maintain code from folders not originating in acre then the above method should be able to accommodate it.

I should state my interest here in that I'd very much like acre to be able to maintain any nominated folder containing apl source somewhere within it _with no additional footprint_. Currently OpenProject recognises a folder if it contains "APLSource" or "acreconfig.txt", rejecting it if neither, adding APLSource if missing, without looking to see if the project or any one or more of its subfolders contains source. If it can do without either one initially there's no reason it shouldn't be able to do without both forever. If it found one or other or both it could act accordingly.

Acre code contains a single uncommented reference to 'APLSource' and none to 'acreconfig'

Convention over configuration.

**Comment by PhilLast** [comment]
Fixed
