### ISSUE TITLE
Latest commit

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#107]
Latest commit:
>  ## Rename source file on change of item name or type
> 
> OpenProject and Refresh will now rename a sourcefile if the item fixed differs from that implied by the filename, casecode if present and filetype, to one that predicts the actual name fixed.
> Plus fixes to fPath and getSource.

Not sure if this deserves the honour of a new release. If you are used to pulling and building the code then you will get it anyway.

This is not entirely in line with the guidelines in the wiki but is a first pass at something workable. The previous Push was just the messaging of what had occurred. This attempts to ensure that it won't happen next time.

If you change the file type of a `.function` to `.operator` [say] without changing the file content, `OpenProject` or `Refresh` will put it back as a `.function`.
If you change it to `.script`, `.array` or `.class` acre will be unable to fix it.
If you change it to `.charlist`, `.charstring` or `.charmat` acre will honour your change and present the content of the file as text in the specified format.

Similar changes and restrictions apply to changes between `.script`, `.class` and `.interface`.

In all cases the new types `.apla`, `.aplf` &c. are read but renamed to the old equivalent with the same provisos as above. This awaits a decision on how and when to change.

Changing the content of a file from operator to function [say] without the corresponding renaming is also reflected in acre's doing the renaming for you and the same compatibilities and incompatibilities obtain.

So much for name class. Changing the name, or casecode where applicable, or the internal name of a defined operation or scripted item without changing the filename also results in acre's renaming of the file.

**Comment by PhilLast** [comment]
> This awaits a decision on how and when to change.

Changing a single `0` to a `1` in one function will make `.apla`, `.aplc` &c the default file types after which `OpenProject` would rename all source files. This might take a while for 10000 files but would be done only once.

**Comment by PhilLast** [comment]
Just tried on CAS7 that usually takes about one and a half minutes to open the first time and eight seconds subsequently while the files are still in cache.

Took an EXTRA four and a half minutes to report on and rename ALL the files and eight seconds after they were in cache and not requiring renaming again.

Reversed the process without encountering a single error.

Currently the renaming process involves ⎕NTIE, ⎕NRENAME & ⎕NUNTIE for every file. Should be quicker in v17.0 with ⎕NMOVE, maybe.

**Comment by norberturkiewicz** [comment]
@PhilLast is the rename a purely an extension change or will it also drop case encoding?

**Comment by PhilLast** [comment]
With `keephistory` off and at present, if
`/a-0/b-0/item0-0.function` fixes as _operator_ `Item1` because of an external edit `OpenProject` will rename it to
`/a-0/b-0/Item1-1.operator` if `casecode` is on and as
`/a-0/b-0/Item1.operator` if `casecode` is off.
If it is subsequently edited in APL it will be written as
`/a-0/b-0/Item1-1.operator` with casecodes or as
`/a/b/Item1.operator` without.

Renaming is done by `OpenProject` and `Refresh`. Edit with `keephistory` off writes a new file if the original doesn't match.

With `keephistory` on it's slightly different at present but will change.

**Comment by PhilLast** [comment]
Fixed
