### ISSUE TITLE
LENGTH ERROR on acre.refresh project with no source files.

### ISSUE THREAD

**Issue by e9gille** [the-carlisle-group/Acre-Desktop#109]
https://github.com/the-carlisle-group/Acre-Desktop/blob/6d7b2ada1827537b5f879f6fdf43c1dcaed9be63/APLSource/_code-0/getSource-8.function#L16

https://github.com/the-carlisle-group/Acre-Desktop/blob/6d7b2ada1827537b5f879f6fdf43c1dcaed9be63/APLSource/_code-0/fixValue-8.function#L1

fixValue returns shape 3, should be 4.

**Comment by PhilLast** [comment]
Fixed release will be v4.5.1.014
