### ISSUE TITLE
List of Items Recently Changed

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#11]
In old versions of acre, a list of the fully qualified names of functions loaded from change files would spill into the session on opening.  This doesn't happen now, and that is good. 

However, it is extremely useful to have a way to get a list of items recently worked on. This is how I know what the heck I was doing on Friday when I arrive at work Monday morning.  I suggest  something like:

~~~
      ]Acre. Changes projectspace
#.CarlisleGroup.FlipDB.Foo1
#.CarlisleGroup.FlipDB.Foo2
...etc.
~~~

In fact, perhaps this should be combined with ]History, we could use the same command for both; GIve it a project space and you get a list of recent changed items, give it an item and you get the most recent versions of the item - everything always with most recent at the top.

**Comment by norberturkiewicz** [comment]
I agree.  In ACRE 2, I use the menu option to list changes

**Comment by PhilLast** [comment]
`]Changes` already exists in my devt version.
```
      ]changes dfns
 changed              deleted              
 #.dfns.acc           #.dfns.art
 #.dfns.ambiv                        
 #.dfns.at                           
 #.dfns.cf                           
```
The way acre currently defines the syntax for commands preludes the suggested dual use.
Three types of command.
```
]projectcommand project args ...
]itemcommand itemname itemname ...
]sharedcommand args ...
```
Actually it might not. If the projectname is to be replaced by the projectspace then it provides two options for all project and item commands by recognising that it's the space itself rather than a member. It'd have to be decided by the control operators before the method itself were called.

**Comment by PaulMansour** [comment]
Ok, now that we have killed off ProjectName, should we have the same command name for both recent history of an item and the recent history of project?  I vote yes.  We would then have:

~~~
                  ]Changes #.Project
#.Project.Foo1
#.Project.Foo2
#.Project.Foo3 

                   ]Changes #.Project.Foo1
Version 3, saved ...
{source}
Version 2, saved ...
{Source}
etc.
~~~

Note that it is critical that items are listed by change date, with most recent up top, and NOT alphabetically.

**Comment by PhilLast** [comment]
My output above also listed deletions. Do we want them?

**Comment by PaulMansour** [comment]
I would say no.

**Comment by PaulMansour** [comment]
Done
