### ISSUE TITLE
Test_Misc_007

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#113]
Test_Misc_007 is a failing test in acre. It creates a project containing a single function, erases the function outside of acre's remit (`⎕EX`), creates a namespace with the same name populating it with a new function and saves it (`SetChanged`). Acre fails the test by neither recognising nor preventing the situation.

Having implemented Norbert's suggestion that acre not only report a "Not Fixed" event but also suggest that the user examine the files concerned I saved the test project as it was. Here is the output, which no doubt could be improved, from reopening the project. (I have temporarily disabled the `⎕SIGNAL` triggered by certain messages)
```
      ]openproject Test_Misc_007
Opening from C:/Users/Phil/Desktop/acre4projects/Test_Misc_007/
 to #.Test_Misc_007
Please wait - Reading 3 files from .../acre4projects/Test_Misc_007/APLSource
!!! Not fixed .function #.Test_Misc_007.Hello
File: .../Test_Misc_007/APLSource/Hello-1.function may require attention.
#.Test_Misc_007
```
Because acre always creates the namespace tree first the effect will always be that the namespace and its contents take priority over the item they shadow. The user can then edit, rename or move any files to remedy the situation. This would seem to me to be the best outcome we could wish for rather than attempting to forestall the implementation of the user's design aims.

**Comment by aplteam** [comment]
Agreed. Test case amended accordingly.
