### ISSUE TITLE
Acre fails to create project with variables containing nulls.

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#119]
)ns test
#.test
      )cs test
#.test
      3 3⍴⎕null
 [Null]  [Null]  [Null] 
 [Null]  [Null]  [Null] 
 [Null]  [Null]  [Null] 
     t← 3 3⍴⎕null
      )cs 
#
      ]createproject c:\temp\testpro test
 Acre  4.8.0.035  2018-10-25
Added script "quadVars"
* Command Execution Failed: SYNTAX ERROR

**Comment by PhilLast** [comment]
I assume this is something new i that it hasn't been attempted before.

I should probably have put this in a more prominent place but the display ⎕SE.acre._code.aplArrayNotation specifies among other limitations:

> Functions, operators, scripted spaces, classes, interfaces, ⎕NULL and 
results of ⎕OR are either not rendered properly or cause errors.

For some reason this has disappeared from the acre release folder where it was also stored as a text file.

The limitations are specifically about what can be rendered in APLAN as items of arrays or members of spaces. If we can be certain that __⎕NULL=⎕NULL__ returns scalar 1 in all circumstances it can be removed from the above list and replaced by the unquoted literal "__⎕NULL__" in the encoding as for instance:
```
1 'BC' ⎕NULL 'A' (2 3)
```

The others are not likely to be treated unless and until Dyalog's own version of array notation is implemented in the interpreter and released.

To these must be added the fact mentioned recently ('though as I write I can't recall where) that arrays other than charstring, charmat and charlist cannot contain ⎕UCS 0.

**Comment by e9gille** [comment]
Yes, this came up in the Sunday workshop when creating a project from existing source. It wasn't clear why it failed, it just threw a syntax error. There was a request that specific items that cause issues be reported and potentially the reason they fail serialisation.

I believe ⎕NULL=⎕NULL in Dyalog, although this is unusual (other languages typically don't report that as an equality).

**Comment by PaulMansour** [comment]
This is fixed is it not? Can we close?

**Comment by PhilLast** [comment]
Yes. Any array containing ⎕NULL will be stored as APLAN which encodes them simply as `⎕NULL`
