### ISSUE TITLE
CreateProject doesn't say what's not saved.

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#120]
Does CreateProject not display messages when parts of a workspace are not written to a file?

**Comment by PhilLast** [comment]
Acre stores all traditional & direct functions & operators, scripted namespaces, classes and interfaces. Also all arrays except those containing any of the above as items or members of unnamed spaces.
Also any of the _unexcepted_ above that are contained within _named_ spaces that were created with dyadic ⎕NS.
Further exceptions include functions associated through __⎕NA__, derived functions, any array containing ⎕NULL (altough this could be mitigated with a little effort - see issue #119 ) and arrays other than regular text arrays that contain ⎕UCS 0 .

Any workspace can contain countless instances of the exceptions.

Have you encountered further exceptions?
Are there any of the above exeptions that ought specifically to be reported?
