### ISSUE TITLE
CreateProject given a project space in ⎕SE

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#122]
This is inadvertently possible at present because I seem to have failed to prevent it but the resulting project is unusable.

One reason is that acre expects names to begin `#.` . The repurcussions are ridiculous but not worth describing.
 
I can either put a check into __CreateProject__ to prevent it - my preference - or I can do some unpredictable amount work to make _it_ work.

**Comment by norberturkiewicz** [comment]
I would think that we should "discourage" working with code outside of the standard #. userspace.  ACRE can be a reset on implementing some best practices.  

I like @PhilLast technique where he developes code under #... and during a build/test process, it can be copied into []SE.
