### ISSUE TITLE
Acre config file

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#125]
@e9gille l has proposed that we change the name and restrict the encoding of the acre config file.
A reason for fixing the encoding is to make it easier to amend programatically.
_JSON_ and _APLAN_ both return a container space into which we can assign new values rather than a scripted one where we can't. Both require a five step process: _read - decode - amend - encode - write_.

Given that this is an _APL_ system to maintain _APL_ systems I should prefer to use _APLAN_ but 'though the unwritten _Dyalog_ alternative has a lot of headway to make up the decision is still open and namespace definition is possibly the only point of contention. This gives JSON an advantage in that there is no chance that it would need to be changed. But this _is_ a proposal for a change and there's no guarantee there won't be more.

I propose
* that we change the name to _acre.config_
* that we read _acreconfig.txt_ if there is no _acre.config_
* that if acre rewrites the file is does so as _acre.config_
* that we continue to read the three alternatives of _JSON_, _APLAN_ and _APLScript_ (presumed to start with "{", "[" and ":" respectively)
* that if acre rewrites the file it does so using the same encoding unless _APLScript_ was read when _APLAN_ will be used instead.

Note that the "Open" parameter, which is a "charlist", can now be written in _APLAN_ between matching, broken parentheses as:
```
Open←(
    'ProjectA'
    'ProjectB -track=off'
    'ProjectC -dep=off'
    )
```

**Comment by aplteam** [comment]
Yes!

**Comment by norberturkiewicz** [comment]
I would vote that we move to a JAON config file.  I was never happy using the namespace language syntax for the project details.  It should be easily readable and maintainable without needing a special keyboard or syntax knowledge.

**Comment by PhilLast** [comment]
I'd have thought that for most APLers, who are the people who are going to be using it
```
[                                                                                       
   Open←(                                                                               
      'ProjectA'                                                                        
      'ProjectB -track=off'
   )                                                            
   ProjectSpace←'#.Main.Sub'                                                            
]
```
would be at least as easy to read and maintain manually than
```
{                                                                                            
  "Open": [                                                                                  
    "ProjectA",                                                                              
    "ProjectB -track=off"                                                                    
  ],                                                                                         
  "ProjectSpace": "#.Main.Sub"                                                               
}
```
and exactly the same number of almost identical steps are required to do it programatically having distinguished between them by comparison of the initial character.

**Comment by PaulMansour** [comment]
I'm ok with this.
