### ISSUE TITLE
Slight change to OpenProject

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#128]
We can't open a project _under_ another unless the later project is untracked `-track=off`.

In all cases except root projects OpenProject expunges the target space immediately prior to recreating and populating it from the project folder. For root projects it expunges everything.

Is there a good reason why we should do this in the case of opening an untracked project?

If we didn't we could bring in a host of projects all into the same space overwriting only homonyms. They wouldn't be tracked but they'd be there.
```
]openproject A # -track=off
]openproject B # -track=off
]openproject C # -track=off
]openproject D # -track=off
```
At present the above would result in the contents of only D being in #.
If we declined from expunging the target for an untracked project it would be the merge of all four.

If we preceded the above with
```
)CLEAR
]createproject empty # 
```
Then we _would_ be tracking changes all of which would go into `empty/APLSource/` to be moved manually after the session. Or we could even be a bit clever and move unambiguously named items programatically.

The change to make this happen is in  single line of code that's currently commented out.

Takers?

**Comment by PhilLast** [comment]
@PaulMansour @aplteam & @e9gille might recognise the situation that prompted this.

**Comment by e9gille** [comment]
Phil, I know what prompted this, but I don't think your suggestion would be an acceptable solution and it would only confuse matters.

I'll write up my understanding of  the current requirements and send it around.

**Comment by PhilLast** [comment]
> if Acre were to provide lower level tools

While I have your attention. What _is_ an API in terms of something like acre?

We currently have one _manual_ and two programmatical protocols:
```
]acre.command args -options ⍝ with the option of capture as ]result←acre.command ...

result←⎕SE.UCMD 'acre.command args -options'
result←'option' ⎕SE.acre.run arg
```
The third above curently offers
I think I asked this yesterday. I also think I heard a comment regarding the not overwhelming the _run_ function with too many additional options with which in mind I implemented the necessary new controls on messaging as a _command_ rather than an additional option to _run_. There is also a standing desire to restrict the number of _commands_ that acre offers.

I'm loth merely to publish a list of internal functions to call that are currently called under control with known expectations as part of the application. 

So we need a protocol. I'm happy to accept that neither of the above is the best solution. 

Strikes me that a command:
```
]api←acre.API
⍝ and/or maybe
]api←acre.API projectspace
```
could deliver a namespace (call it an instance if you will) with vestigial functions (methods) that call the internals without direct exposure. Reminds me of something ...

What might be better?
