### ISSUE TITLE
Acre-Desktop icon choices

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#13]
Here are the current contenders. 

I like the first one the most.

1. ![acre_abstract_blue-01](https://user-images.githubusercontent.com/5807754/33845799-3b366f2e-de6a-11e7-9abf-3f18d8b75f84.png)
2. ![acrelogo-01](https://user-images.githubusercontent.com/5807754/33845794-3ad415d6-de6a-11e7-9940-f469af2f7fa3.png)
3. ![acrelogo2-01](https://user-images.githubusercontent.com/5807754/33845795-3ae2fdee-de6a-11e7-96ad-96ba64ea8bbc.png)
4. ![acrelogoblue-01](https://user-images.githubusercontent.com/5807754/33845796-3af78cfa-de6a-11e7-9ae7-597ae8cb0e97.png)
5. ![acreorangeoutline-01 1](https://user-images.githubusercontent.com/5807754/33845797-3b101658-de6a-11e7-8b82-bd27a4ed8b87.png)

**Comment by PaulMansour** [comment]
Well, you know I'm a traditionalist, so I like the classic alpha.

I like the way the modern one works more with the cube, but it starts looking like a fish as it gets smaller.

**Comment by norberturkiewicz** [comment]
Blue or green with the traditional alpha?

**Comment by PaulMansour** [comment]
Blue, looks better with Dyalog orange.

**Comment by norberturkiewicz** [comment]
Sounds good.  I'll get the source files and upload to an artwork folder.
