### ISSUE TITLE
Regarding messages

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#131]
I think the latest changes regarding messages went a bit too far; for example, when I enter 

```
]change
```

then _Syntax: ]acre.Changes space | item_ is written to the log - I think this should go to the session. Same for error messages, although I cannot think of any right now.

`]erase ` still prints to the session in case there was something to erase, and that's the way it should be.

For log entries on the other hand I am missing a (leading) time stamp. If you change the same function over and over again and acre stops tracking the changes (something that may happen in a multithreaded application) that might well be difficult to detect without a timestamp.

**Comment by PhilLast** [comment]
Actually _all_ messages are now written to the log and _none_ to the session.

`]erase`, along with all acre commands returns a result and along with almost all _item_ commands, which most acre commands are, returns the FQNs of items affected.

At present there is _almost_ no differentiation between different types of message. It was suggested and implemented a few months ago without objection that _error_ messages should cause the command to signal an error after completing as much of the task as it could. This begged the question of what constituted an _error_ message so some messages that had been prefixed with "!" for emphasis were deemed to be _error_ messages, some had "!"s removed to demote them and others added to promote them but no exercise was undertaken to decide the issue properly.

If anyone had a strict semantic definition to decide which acre messages constitute _errors_, _warnings_ and _informational_ messages then different prefixes could be applied to them and different behaviors assigned to each type.

> For log entries on the other hand I am missing a (leading) time stamp. 

Implemented for next release. Please object here if you see fit.
>2018-11-25 17:40:08 Please wait - Reading 5 files from .../acre4projects/test/APLSource
2018-11-25 17:40:08 Opening from .../Desktop/acre4projects/test to #.test
2018-11-25 17:39:58  Acre  5.0.0.072  2018-11-22  10.27
