### ISSUE TITLE
AcreConfig 

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#133]
The presence of the _#.project.AcreConfig_ space:
```
      ]openproject project
#.project
      #.project.AcreConfig
#.[Namespace]
      ]toaplan #.project.AcreConfig
[
   CaseCode←'Off'
   KeepHistory←'On'
   Open←''
   ProjectFolder←'C:/Users/User/projects/project/'
   ProjectSpace←'#.project'
   StartUp←''
]
```
  created into a project by OpenProject can confuse other software that lists the contents of a namespace or project.

All the information to recreate it exists in the hidden project dataspace that acre keeps for a tracked project so it could be re-instated immediately on demand. This could be by a command `]config` [say] or as an addition to the new `⎕SE.acreAPI.`functions:
```
      api←⎕SE.acreAPI
      ⊢pc←api.config #.project
#.[Namespace]
      api.toaplan pc
[
   CaseCode←'Off'
   KeepHistory←'On'
   Open←''
   ProjectFolder←'C:/Users/User/projects/project/'
   ProjectSpace←'#.project'
   StartUp←''
]
```
The semi-permanent ref could then be deprecated and removed at a later release.

Were a particular value from the ref (ProjectFolder [say]) to be in regular use the following:
```
      (⎕SE.acreAPI.config #.project).ProjectFolder
```
would retrieve it without cluttering the ws with extraneous other stuff.

**Comment by e9gille** [comment]
The primary reason for the addition of this space was that I requested a portable way for a package to access files from its project folder. I guess your suggested approach would work, but I'd like it to be more natural to use in project code. Compare:
```
AcreConfig.ProjectFolder
vs
(⎕SE.acreAPI.config ⎕THIS).ProjectFolder
```
Also, with the current approach it is easier to target all references to the ProjectFolder.

Specifically, for a distribution version of a Project (ie. for an application) the ProjectFolder for the main project and its packages should be a path relative to the main project folder. That way, when you build a dws or exe, you can make sure that the actual application folder can be moved without affecting access to the resources.

For the [APL Language Server](https://github.com/OptimaSystems/apl-language-server) I built, I used the technique of replacing the ProjectFolder path string in all project spaces with a trad fn that returned the WSID prefixed relative path. The server is embedded in a VSCode extension that is downloaded and installed by VSCode somewhere on a users computer (different location based on platform). I don't need to know where it is, but using relative paths was key to making it work anywhere.

Note that I coded it in a rush and it isn't documented nor commented, but the Build function is [here](https://github.com/OptimaSystems/apl-language-server/blob/master/APLSource/Build-1.aplf) if you dare to look.

**Comment by PhilLast** [comment]
The primary reason for the objection chimes with my general reluctance to inject stuff into the project for any reason.

> `quadvars` is equally objectionable to me not for the name which is mutable or the technique which rather could be a recommendation but for the fact that acre is imposing the thing onto the project itself.

But having read your response I now have an experimental function that, although still in ⎕SE.acre, is niladic and uses ⎕NSI to determine the project whence it's been called and returns the appropriate project config space.
```
      ]openproject test
#.test
      test.this.n.that.{ ⎕SE.acre.config }0
#.test.[Namespace]
      test.this.n.that.{ ⎕SE.acre.config.ProjectFolder }0
C:/Users/user/projects/test/
```
So within the project code you'd require only `⎕SE.acre.config.whatever`
In fact the function _could_ be fixed directly into `⎕SE` as `⎕SE.acreConfig`

**Comment by PhilLast** [comment]
apologies for the first five words of my response which were not intended as a parody. The words were in my head and I didn't think to wonder where they came from.

**Comment by PhilLast** [comment]
Of course what I've just remembered is that this will only work inside a currently tracked project and the idea is that it can be saved in a ws with the project by a build process when such will _not_ be available.

**Comment by e9gille** [comment]
> apologies for the first five words 

No need, I had to scroll up to see what you referred to :)

>general reluctance to inject stuff into the project for any reason.

I agree, but at the same time I'd rather not refer to `⎕SE.acre` in project code. I think an Acre reserved namespace is a good compromise, unless someone can come up with a better option.

**Comment by aplteam** [comment]
I would rather prefer to refer to `⎕SE.acre` then having something popping up out of nowhere.

I have never suffered from the first option, but I have suffered from the second option.

**Comment by e9gille** [comment]
I don't know if a typical project would need to refer to its project folder particularly often, but whatever solution we settle on, the important thing is that a build/distributable version works. Having references to `⎕SE.acre` in a `dws` or `exe` would probably not be a nice solution. I guess a build process could replace references to `⎕SE.acre` in code with something else, but I prefer the injected namespace approach to something like that.

**Comment by aplteam** [comment]
Paul requested it, so I don't know for sure, but my guess it that this is a rare event, and that it will be done "manually".

**Comment by e9gille** [comment]
Having slept on this I still can't come up with better a better suggestion, so I'll simply re-iterate the argument in the hope it jogs some ideas in other heads.

1. A project/package may need access to files in its project folder.
2. A package will likely (yet to be implemented) be stored in a subfolder of another project.
3. A distributable (application) might not have access to Acre framework code.
4. The current implementation forces a user to refer to its project space to access the project configuration file (eg. `##.##.AcreConfig.ProjectFolder`). With classes, in particular instances thereof, you have to be even more explicit about the search path (currently done via `(⊃⊃⎕CLASS ⎕THIS).##` or similar). This would also need to be considered if you were to return it dynamically via `⎕SE.acreConfig`.

I guess another option would be to have the build script add a bootstrap function that sets up a copy of `⎕SE.acreConfig` before launching the app. If the function operates in isolation without dependencies on the rest of the acre codebase then it might just work.

Essentially, `acreConfig` would need to check where it is called from (using something like`⍕{9.2=⎕NC⊂,'⍵':⊃⊃⎕CLASS ⍵ ⋄ ⍵}⊃⎕RSI`) and then look up the space against a map. That means acre may need to remember untracked projects as well as tracked ones (assuming that is how you plan on providing the dynamic feature).

**Comment by PaulMansour** [comment]
Ok, I'm joining the party.

I don't (I think) have a problem with removing the AcreConfig and putting it somewhere else. In fact, you could probably get rid of the whole thing, as I currently have to read it and assign it myself as I have other items in there, like version, and Acre only populates stuff it knows about (I have been meaning to ask for an enhancement here). Plus I add more stuff in there dynamically.  (Though I wonder if this is the right place to store the version)  

I have solved the runtime/application issue as follows.  I have a concept of an **application**, which is a folder containing the **application worspace** that has all the code of all the packages pre-loaded. In addition, the application folder contains stripped down subfolders for all the packages - no APL code, just other packages assets (bitmaps, dlls, etc.).  (note that "application" here is not a windows install or anything, just ws and collection of folders built from packages ) The application ws knows the list of relative paths to the packages, but only the knows the absolute path at run time, as we must know where the application ws actually resides.  It is the job of QuadLX in this workspace to load all the acre config files of the packages and set them into their respective projects spaces, which already exist.

I have code in my AcreTools project that formalizes all of this, in what I hope is a generic solution that others could find useful.  My original thought that much of this should go into Acre itself, but mayby not.

Regardless of what Acre does, I think I will have a config namespace of some sort in each projects space, and it makes sense that this is essentially the acre config file. No matter what, I need the folder where the resources for a project are.  

As I write this, when it comes down to it, the only really important thing in acre config is the path to the project/package folder, which must be arrived at in two different ways in dev vs runtime.  I may well rethink my whole approach.

**Comment by PaulMansour** [comment]
Agreed we must keep as is.
