### ISSUE TITLE
How to add new items to a tracked project

### ISSUE THREAD

**Issue by jwied** [the-carlisle-group/Acre-Desktop#137]
As a consequence of my impressions from the conference in Belfast, I built a prototype to manage the source code a given application with ACRE.
Next to positive feedback, I also got one special issues, that I want to ask as a question here:
**How can a new function be added to the project folder automatically, when this was done not with the editor?** For example by using the line editor (∇) or by )COPYing it from another workspace.
The ]refresh command is doing such a sync only from the folder into the namespace, but not in the other direction.

**Comment by PhilLast** [comment]
Hello and Welcome.
```
]SetChanged #.project.space.function
```
This can be used for any item including arrays that cannot be changed in the editor such as numeric, mixed or those more deeply nested than depth two lists of strings.

**Comment by jwied** [comment]
Perfect, that helps.
