### ISSUE TITLE
Acre's help functionality

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#138]
Acre supports the `]?acre.{command}` syntax but it does not support the newly introduced syntax 17.0 came with:

```
]acre.{command} -?
]acre.{command} -??
]acre.{command} -???
```

It should.

Note that the `]?` syntax is now deprecated and will disappear one day.

**Comment by PhilLast** [comment]
Acre currently doesn't support v17.0 any more than it does v17.1, v18.0 or v21.0 except insofar as it might just happen to work.

But with regard specifically to `]?command` I should have assumed, _wrongly I suppose from the above_, that SALT or SPICE or whatever governs it would have been amended to perform the identical operation from either syntax without any intervention from user command designers merely by calling the `Help` function from within the script.

That's certainly the way I should have done it.

**Comment by aplteam** [comment]
Yes, that's what they did. All I am saying is that the old syntax is
deprecated and will eventually disappear. Not now.

**Comment by PhilLast** [comment]
> but it does not support the newly introduced syntax 17.0 came with:
> [...]
> It should.

I haven't seen v17.0.

Are you saying that `]acre.openproject -?` gives an error, does nothing or does exactly the same as `]?acre.openproject`
?

**Comment by aplteam** [comment]
I have no idea what has happened yesterday: today 

```
]acre.CreateProjects -?
```

works just fine. Maybe I have tried to execute it in 15.0 ;)

Case closed.
