### ISSUE TITLE
Acre does not store a Namespace script with nested namespaces

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#141]
Message

```
 Not stored by acre                                                                       ⎕NC
=============================================================================================
 #.CAS.PDFTOOLS.XCPro40_Declares.Constants                                                9.1
 #.CAS.PDFTOOLS.XCPro40_Declares.Functions                                                   
 #.CAS.PDFTOOLS.XCPro40_Declares.Structures                                                  
 #.CAS.PDFTOOLS.XCPro40_Declares.Constants.Functions                                         
 #.CAS.PDFTOOLS.XCPro40_Declares.Constants.Structures                                        
 #.CAS.PDFTOOLS.XCPro40_Declares.Functions.Constants                                         
 #.CAS.PDFTOOLS.XCPro40_Declares.Functions.Structures                                        
 #.CAS.PDFTOOLS.XCPro40_Declares.Structures.Constants                                        
 #.CAS.PDFTOOLS.XCPro40_Declares.Structures.Functions                                        
 #.CAS.PDFTOOLS.XCPro40_Declares.Init                                                     3.1
 #.CAS.PDFTOOLS.XCPro40_Declares.Constants.Functions.InitNA                                  
 #.CAS.PDFTOOLS.XCPro40_Declares.Constants.Functions.LoadLibraries                           
 #.CAS.PDFTOOLS.XCPro40_Declares.Functions.InitNA                                            
 #.CAS.PDFTOOLS.XCPro40_Declares.Functions.LoadLibraries                                     
 #.CAS.PDFTOOLS.XCPro40_Declares.Structures.Functions.InitNA                                 
 #.CAS.PDFTOOLS.XCPro40_Declares.Structures.Functions.LoadLibraries                          
 #.CAS.PDFTOOLS.XCPro40_Declares.Constants.PXCp_CreationDisposition_Overwrite             2.1
 #.CAS.PDFTOOLS.XCPro40_Declares.Constants.PXCp_CreationDisposition_Skip                     
 #.CAS.PDFTOOLS.XCPro40_Declares.Constants.PXCp_Write_NoRelease                              
 #.CAS.PDFTOOLS.XCPro40_Declares.Constants.PXCp_Write_Release                                
 #.CAS.PDFTOOLS.XCPro40_Declares.Constants.Structures.PXCp_CopyPageRange                     
 #.CAS.PDFTOOLS.XCPro40_Declares.Functions.Constants.PXCp_CreationDisposition_Overwrite      
 #.CAS.PDFTOOLS.XCPro40_Declares.Functions.Constants.PXCp_CreationDisposition_Skip           
 #.CAS.PDFTOOLS.XCPro40_Declares.Functions.Constants.PXCp_Write_NoRelease                    
 #.CAS.PDFTOOLS.XCPro40_Declares.Functions.Constants.PXCp_Write_Release                      
 #.CAS.PDFTOOLS.XCPro40_Declares.Functions.Structures.PXCp_CopyPageRange                     
 #.CAS.PDFTOOLS.XCPro40_Declares.Structures.PXCp_CopyPageRange                               
 #.CAS.PDFTOOLS.XCPro40_Declares.Structures.Constants.PXCp_CreationDisposition_Overwrite     
 #.CAS.PDFTOOLS.XCPro40_Declares.Structures.Constants.PXCp_CreationDisposition_Skip          
 #.CAS.PDFTOOLS.XCPro40_Declares.Structures.Constants.PXCp_Write_NoRelease                   
 #.CAS.PDFTOOLS.XCPro40_Declares.Structures.Constants.PXCp_Write_Release                     
 Acre  5.0.0.077  2018-11-28  14.38
```

Source

```
:namespace XCPro40_Declares

    ∇ Init
      Functions.InitNA
    ∇

    :namespace Constants

        ⍝ PXCp_CreationDisposition
        PXCp_CreationDisposition_Skip		←  1
        PXCp_CreationDisposition_Overwrite	←  2

        ⍝ PXCp_WriteDocFlag
        PXCp_Write_Release		← 0
        PXCp_Write_NoRelease	← 1

    :endnamespace

    :namespace Structures

        ⍝ structures
        PXCp_CopyPageRange←'<{U4 U4 I4 U4}[1]'

    :endnamespace

    :namespace Functions

        ∇ LoadLibraries;_
          ⍝ load librarys
          'LoadLibrary'⎕NA'u kernel32|LoadLibrary* <0T'
          _←LoadLibrary⊂#.U.BinDir,'\dscrt40.dll'
          _←LoadLibrary⊂#.U.BinDir,'\xccdx40.dll'
          _←LoadLibrary⊂#.U.BinDir,'\ixclib40.dll'
          _←LoadLibrary⊂#.U.BinDir,'\pxclib40.dll'
          ⍝
        ∇

        ∇ InitNA
          LoadLibraries
          ⍝ associate functions
          ⎕NA'P ',#.U.BinDir,'\xcpro40.dll|PXCp_Init =P <0T1[] <0T1[]'     ⍝ must pass single byte unicode
          ⎕NA'P ',#.U.BinDir,'\xcpro40.dll|PXCp_ReadDocument* P <0T[] U4'
          ⎕NA'P ',#.U.BinDir,'\xcpro40.dll|PXCp_GetPageLayout P >P'
          ⎕NA'P ',#.U.BinDir,'\xcpro40.dll|PXCp_GetPagesCount P >U4'
          ⎕NA'P ',#.U.BinDir,'\xcpro40.dll|PXCp_InsertPagesTo P P ',##.Structures.PXCp_CopyPageRange,' U4 U4'
          ⎕NA'P ',#.U.BinDir,'\xcpro40.dll|PXCp_WriteDocument* P <0T[] I U4'
        ∇
    :endnamespace

:Endnamespace
```

**Comment by PhilLast** [comment]
If I'm not mistaken the namespace `#.CAS.PDFTOOLS.XCPro40_Declares` is itself being stored. 

I did seek clarification on this but perhaps I was too vague or insufficiently persistent in my requests but so far as I could understand when I was being asked to report on items _not_ stored by acre I was being asked to report the name of _every_ item in the original space that acre would not store _individually_.

`CreateProject's` search for candidates to store produces a list of all globally exposed arrays, functions, operators, namespaces, classes and interfaces as far down the tree as it's possible to go.

It then filters the list according to specific nameclasses 2.1 3.1 3.2 4.1 4.2 9.1 9.4 9.5 rejecting external, derived or primitive objects; namespace or function refs; non-scripted spaces; and members of scripted spaces & classes. Everything removed from the list is then reported as not having been stored.

So far as I can tell all the above names refer to sub-spaces, functions and arrays within `XCPro_Declares` itself and as such are not stored individually.

Acre _could_ do a fair amount more work to reduce the list of reported rejections to some agreed subset but it seemed most important to concentrate on what it _does_ store and just report everything else.

**Comment by aplteam** [comment]
The way I see it it should be a very important warning. That implies that it mentiond only objects that are not stored at all.

In a message like the one above it is actually very hard to spot any **real* problem.

**Comment by PhilLast** [comment]
I'm guessing that my putative _'agreed subset'_ would be empty.
If you're looking for problems you'll find them in the list:
```
Can't format           ⎕NC
===== ======           ===
#...                   ...
``` 
which in all likelihood won't appear _(at least I hope not)_ as it's a catchall for errors in formatting items for storage in source files. Anything occurring here will hint at a bug in acre or APLAN.

What appears under `Not stored by acre` are listed above but to elaborate:
* __external, derived or primitive objects__ - results of ⎕NA; assignment of compositions: `ave←+⌿÷≢`, `twice←⍣2`; and of primitives: `log←⍟`, `power←*`
* __namespace or function refs__ - local naming of remote items: `UT←##.Utilities`, `fd←UT.FormatDateTime`  
* __non-scripted spaces__ - container spaces that are the result of dyadic ⎕NS; their members are stored individually and they leave no footprint if empty.
* __members of scripted spaces & classes__ are stored within the script and require no further attention by acre.

**Comment by aplteam** [comment]
I see.

Two questions:

1. Should go this (not stored I mean) into the log file but not be printed to the session (hopefully soon)? Too much informatiion hurts in this case.  (Could there be a =verbose flag perhaps if one really wants that?)

2. Should what you wrote above go into the documentation?

**Comment by PaulMansour** [comment]
Done
