### ISSUE TITLE
Future releases

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#144]
Until now each release has included the zipped installation folder containing the acre workspace (_acre.dws_), the acre command script (_acre.dyalog_) and the release notes (_releaseNotes.txt_).

The acre project folder now contains the build workspace (_build.dws_) that produces the acre workspace for the specific Dyalog version (_[localappdata]/acre/acre[ver]/acre.dws_) that itself produces the script and notes.

@PaulMansour @norberturkiewicz @aplteam Does it make sense for releases to continue to include the installation folder when it can be built on site and each Dyalog version used requires is own dedicated installation?

I need to make a new release including the fixes to the bugs announced so should like an answer soon or could just continue as before.

**Comment by aplteam** [comment]
No idea,

BTW, I will always just go for the oldest version I need to support (15.0 for me) and use that workspace everywhere.

**Comment by norberturkiewicz** [comment]
I think we should keep distributing the release version.  No need to make it a hurdle for new users.

**Comment by PhilLast** [comment]
I forgot to mention in the notes that new release 5.0.6+137 has a zipped Dyalog 14.0 installation folder.

**Comment by PhilLast** [comment]
And I can't find anywhere I've mentioned that my comment above
> each Dyalog version used requires is own dedicated installation

is no longer true and a v14.0 installation can be used just as effectively with v16.0 and probably v17.0 also as the faster code applicable to each later interpreter is swapped in at startup.

**Comment by PaulMansour** [comment]
Done
