### ISSUE TITLE
Custom acre.config fields are omitted.

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#147]
Testing in v14, it looks like anything not in

```
 configFields←{⍺←⊢
     {
         ⍵.CaseCode←'Off'     ⍝ integer suffix to name elements
         ⍵.KeepHistory←'Off'  ⍝ store .change- and .delete-files
         ⍵.ProjectSpace←''    ⍝ #[.path]
         ⍵.Open←''            ⍝ Open with this project
         ⍵.StartUp←''         ⍝ executed after OpenProject
         ⍵
     }#.⎕NS''
⍝ ⍵ ?
⍝ ← config space
⍝ Phil 2018-06-06 21.11
 }
```

will be omitted from the AcreConfig namespace.

**Comment by PaulMansour** [comment]
Indeed, I've been meaning to mention this for a while. I just end up reading the file myself.... but it would be nice if Acre just read in everything. It's not a security thing is it?

**Comment by norberturkiewicz** [comment]
I don't believe so.  If we're worried about security we can nest all custom data under a subnamespace.

I.e.

```
configFields←{⍺←⊢
     {
         ⍵.CaseCode←'Off'     ⍝ integer suffix to name elements
         ⍵.KeepHistory←'Off'  ⍝ store .change- and .delete-files
         ⍵.ProjectSpace←''    ⍝ #[.path]
         ⍵.Open←''            ⍝ Open with this project
         ⍵.StartUp←''         ⍝ executed after OpenProject
         ⍵.Custom.Name←''
         ⍵.Custom.Path←''
  ⍵
     }#.⎕NS''
⍝ ⍵ ?
⍝ ← config space
⍝ Phil 2018-06-06 21.11
 }
```

I think version should be a first-class property.

**Comment by PhilLast** [comment]
More a request for enhancement than a bug I should have thought. No-one ever asked for it before. But simple enough to do if required. 

Acre reads in the whole space, extracts what it needs as lower-case-named vars and throws the space away, finally reconstituting the ideal with defaults and correct capitalisation before cloning it for the exposed _#.[project].AcreConfig_.

So there's currently a congruence between _#.[project].AcreConfig_ and the internal values stored for the project that would have to be broken at an early stage of opening a project. 

What we have is a half-way-house between what you're asking for and the more cautious way of handling config files to report an error if there's anything there that isn't recognised in case it disguises a typo. Acre just ignores it.
> I think version should be a first-class property.

I'm afraid I don't understand this request. What is a first-class property in this context? Are you asking for another value to be injected into _AcreConfig_? Is _version_ that of _Dyalog_, _Acre_ or some property of the project?

**Comment by PaulMansour** [comment]
Indeed, enhancement not bug!

**Comment by PhilLast** [comment]
And will be done as such. If Norbert can let me know what is the business about _version_ I can do that at the same time. But you might not know that at present both of:
```
      'version'⎕se.acre.run''
 Acre  5.0.5+125  2019-02-12  23.37
```
and
``` 
      ⎕se.acreAPI.version''
 Acre  5.0.5+125  2019-02-12  23.37 
```
return a four item list that might be what you want. I hope to deprecate the former (that is _⎕SE.acre.run_) as _⎕SE.acreAPI_ is more flexible, echoes the same functionality and is easier to add more.

**Comment by norberturkiewicz** [comment]
Bad naming convention on my part (maybe)  I referred to first class properties as items required/expected by acre vs misc. data we put in.

**Comment by PhilLast** [comment]
Currently _CaseCode, KeepHistory, ProjectSpace, Open & StartUp_ are all added if they are not present in any case-agnostic version and their names and values are normalised: e.g. _'open', 'oPen' & 'OPEN'_ all become _'Open'_ while _'on', 'oN' & 'ON'_ become _'On'_. _ProjectFolder_ is also added.

Will the continued addition/normalisation of the key values along with the exact mirroring of any others fulfil the requirement?

**Comment by norberturkiewicz** [comment]
> Will the continued addition/normalization of the key values along with the exact mirroring of any others fulfill the requirement?

I can't think of any reason that wouldn't work.

**Comment by PhilLast** [comment]
Have implemented request in development insofar as file `.../MyProject/acre.config` 
```
[
    casecode←'on'
    CuStOmFiElD←'this'
    projectSPACE←'#.myproject
    ...
]
```
results in namespace `#.myproject.acreConfig`:
```
[
    CaseCode←'On'
    CuStOmFiElD←'this'
    ProjectFolder←'.../MyProject/'
    ProjectSpace←'#.myproject
    ...
]
```
In other words, expected fields are "corrected" for case while all others are cloned and "ProjectFolder" is added.

As to requested "Version", if it's still required, is it the result of `⎕se.acreAPI.version''` or something else?

**Comment by norberturkiewicz** [comment]
We're using Version to keep track of each individual projects versioning.

**Comment by PaulMansour** [comment]
Done.
