### ISSUE TITLE
Possible git hooks into acre operations [discussion]

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#149]
I'm exploring the possibility of acre doing git commits and warning if the user has switched branches mid-session.  I'll put these hooks in a personal branch but it may make sense to put in an option in the core.

If git extensions are enabled...

1.  Keep note of the branch project branch when first opened.  Check the current branch before adding, deleting or modifying a file.  Present a warning if the branch differs from the original.  This can lead to a state of unsync,

2.  Put in a git commit every time a file is modified.

3. Add new funciton files to git tracking on fix and commit.

Thoughts?

**Comment by aplteam** [comment]
Paul and I have both implemented Git Tools that can be used alongside acre without a probem.

I think acre should stay agnostic of any tools used. When Dyalog will finally come with its own approach (replacing acre I mean) it will certainly also be agnostic.

**Comment by norberturkiewicz** [comment]
Makes sense.  I'll stick with my custom buildsl
