### ISSUE TITLE
User defined OnFix and OnAfterFix Callbacks

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#152]
Provide Acre settings for onFix and onAfterFix callbacks. Provide way for cancelling save, etc.

**Comment by PhilLast** [comment]
```
      )clear
clear ws
      fix←{1⊣⎕←⍵}
      after←{1⊣⎕←⍵}
      ('⎕se'⎕WG'editor').(onFix onAfterFix)←'#.fix' '#.after'
      ⎕ed 'qwerty' ⍝ a new fn
 ⎕SE.[SessionEditor]  Fix   qwerty←{  ⍝ new fn  }   #  qwerty  qwerty 
 ⎕SE.[SessionEditor]  AfterFix    #  qwerty  qwerty
⍝ escape and function is fixed 
      ⎕nr 'qwerty'
  qwerty←{  ⍝ new fn   } 
      fix←{1⊣⎕←⍵}
      after←{0⊣⎕←⍵}
      ⎕ed 'qwerty' ⍝ a and make a change
 ⎕SE.[SessionEditor]  Fix    qwerty←{  ⍝ new fn  ⍝ make this change   }   #  qwerty  qwerty 
 ⎕SE.[SessionEditor]  AfterFix    #  qwerty  qwerty 
⍝ stays in editor on escape
      ⎕nr 'qwerty'
  qwerty←{  ⍝ new fn  ⍝ make this change   } 
⍝ but has fixed the change
⍝ shift escape doesn't call fix or after
      fix←{0⊣⎕←⍵}
      after←{1⊣⎕←⍵}
      ⎕ed 'qwerty' ⍝ a and make a change
 ⎕SE.[SessionEditor]  Fix    qwerty←{  ⍝ new fn  ⍝ make this change  ⍝ make another change   }   #  qwerty  qwerty 
⍝ stays in editor on escape
      ⎕nr 'qwerty'
  qwerty←{  ⍝ new fn  ⍝ make this change   } 
⍝ and hasn't changed
⍝ shift-escape
      fix←{0⊣⎕←⍵}
      after←{0⊣⎕←⍵}
      ⎕ed 'qwerty' ⍝ and make a change
 ⎕SE.[SessionEditor]  Fix    qwerty←{  ⍝ new fn  ⍝ make this change  ⍝ try again   }   #  qwerty  qwerty 
⍝ stays in editor
      ⎕nr 'qwerty'
  qwerty←{  ⍝ new fn  ⍝ make this change   } 
⍝ still not changed
⍝ shift-escape
```
From the above and a few other unrecorded minor changes to _fix_ and _after_ I infer that:
* not returning a result or returning anything but zero from both callbacks fixes the changes having supplied the new value in _fix_ and empty in _after_. 
* returning zero from _fix_ irrespective of _after_ neither fixes the item nor leaves the editor on escape.
* returning zero solely from _after_ fixes the item but stays in the editor until shift-escape.

What conclusions can be drawn from the above _vis-à-vis_ enabling _user-exits_, _hooks_, _user-callbacks_ whatever; what resources they would need ( Norbert's _checkGitState_ requires only the path to the source folder ) ; and to what extent they should prevent or replace acre's current actions; demand significantly more thought.

**Comment by aplteam** [comment]
Since I was the one who put forward the idea of having a general hook of kinds I must say that now I wonder whether we should avoid opening this can of worms.

I am still keen to automatically commit any changes I make but I wonder whether having a global acre config file that allows setting an entry like, say, "AutoGitCommit" accordingly might be a simpler way to achieve that.

**Comment by norberturkiewicz** [comment]
> I am still keen to automatically commit any changes I make but I wonder whether having a global acre config file that allows setting an entry like, say, "AutoGitCommit" accordingly might be a simpler way to achieve that.

I think this goes along the lines of my previous proposals of introducing minor Git/SVN hooks into Acre. Working on two laptops, one with and one without the hook, I can tell you that it's very nice having those warnings.

**Comment by PhilLast** [comment]
Recent commit ` Acre 5.0.11+165 2019-04-05 23.40` may be on the right lines to satisfy this.

**Comment by PhilLast** [comment]
Please re-open if recent changes did not pass muster.
