### ISSUE TITLE
SetChanged does not leave a trace in the acre log

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#155]

**Comment by aplteam** [comment]
And neither does `CreateProject`. All commands should leave a trace in the log.

**Comment by PhilLast** [comment]
Given that `SetChanged` is capable of writing sourcefiles for anything from a single item; to the contents of a new namespace copied from elsewhere; to all the members of a project; and returns the entire list of them, what should be the message?
```
SetChanged wrote 1 sourcefile
```
and
```
SetChanged wrote 99 sourcefiles
```
or
```
SetChanged
==========
#.project.space.item0
#.project.space.item1
...
#.project.space.item99
```
or what?

**Comment by PhilLast** [comment]
With respect to the absence of messages also from `CreateProject` I suspect that there is a larger number of commands that, in normal circumstances, _don't_ issue messages than of those that do.

In general, acre messages are issued for exceptions. Most that aren't are probably hangovers from when acre was unnecessarily a lot more verbose than it is now. 

Would anyone identifying an absence of  a useful message please also suggest what it ought to be?

Also - should messages identify the command that issued them? Or perhaps repeat the command and even its arguments, options and switches before any other messages it issues?

**Comment by PhilLast** [comment]
My offer of arguments, options and switches I hope is seen as extravagant for every message. The arguments are available directly but the options would require a quite complex and separate computation for each call of each command.

Nevertheless the request that _All commands should leave a trace in the log_ fairly demands either the gist of what was entered or a meaningful message prefixed with the command name else the message would be unidentifiable.

**Comment by PhilLast** [comment]
Fixed by above commit
