### ISSUE TITLE
What's the difference between the API methods "change" and "changefile"?

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#156]
There seems to be none.

**Comment by PhilLast** [comment]
Assume you mean `⎕SE.acreAPI.changes` which replicates the `]acre.changes` command but for the `-when` option and a syntax error that I've just corrected.

`⎕SE.acreAPI.changefile returns the changefile names of the first item in its argument.

**Comment by PhilLast** [comment]
Closed
