### ISSUE TITLE
Minimum Requirements

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#16]
I think the [landing page](https://github.com/the-carlisle-group/Acre-Desktop/blob/master/README.md)  should mention minimum Dyalog APL requirements.  @PhilLast do we know how far back Acre Desktop is compatible or is this a V16 clean slate start?

**Comment by PaulMansour** [comment]
I'm using it with V15, so far no problems.

**Comment by PhilLast** [comment]
Don't have 16 yet. Too much of a temptation to start using @ and a  few other bits and pieces.

**Comment by PaulMansour** [comment]
Ok, so v15 is minimum APL?

**Comment by norberturkiewicz** [comment]
@PaulMansour @PhilLast , is this limited to Unicode only?  

I'd like to add this to our readme and close the ticket.

**Comment by PhilLast** [comment]
You mean acre desktop in general?

I haven't hesitated to use 819⌶. I think that's Unicode only. What else is restricted?

**Comment by norberturkiewicz** [comment]
@PhilLast  AcreDesktop

**Comment by norberturkiewicz** [comment]
I'm going to close this out and add a minimum requirements blurb to the readme
