### ISSUE TITLE
Acre's "Refresh" command

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#163]
Acre's `Refresh` command does not fully refresh the project: it does bring in any changes but it does **not** delete anything from the workspace.

Let's look at an example in order to discuss the implications:

1. Somebody else made some changes to an acre project. As a result of the changes a test case became superfluous.

1. After you pulling, merging and executing acre's `]acre.Refresh` command you have the changes in your workspace, but the test function is still there. Therefore, if you run the test cases, that test case will fail, assuming that a test framework identifies test functions by naming convention.

   It is relatively easy to imagine other real-world scenarios when this would become an issue as well but this example should do.

Acre can work out what was deleted by compiling a list of items in the workspace and then comparing the list with what's in the `APLSource\` folder.  It _could_ then delete what has no associated file.

However, when someone takes advantage of acre's setup feature in order to bring in stuff that should not be tracked or cannot be saved by acre anyway (like `total←+⌿`) then those would all disappear as well.

An additional danger is that a user running into the failing test case might try to fix the test case by changing it in the editor which would made acre save that function - now it's back in the project!

I can see these options:

1. Acre remains unchanged but the documentation (and probably also `]acre.Refresh -?`) provides a warning regarding the limitations of that command.

1. `]acre.Refresh` deletes everything that does not have an associated file in `APLSource\`. The documenation then could point out that the user might want to run the setup function  again.

1. `]acre.Refresh` provides a list of APL objects that have not an associated file in `APLSource\` and leaves it to the user to take action based on this information.

1. The `]acre.Refresh` command is removed altogether. That is a possibility because closing and re-opening a project is not a big deal.

My preference is number 2 since I do not take advantage of the setup feature anyway. If that's rejected I would vote for getting rid of `]acre.Refresh` altogether.

**Comment by PhilLast** [comment]
Have clarified wiki entry for Refresh. Any other option works directly against the command's existence.

**Comment by PhilLast** [comment]
Closing this as answered.
