### ISSUE TITLE
Installation fails on non-windows platforms

### ISSUE THREAD

**Issue by e9gille** [the-carlisle-group/Acre-Desktop#165]
With the introduction of fso (FileSystemObject) in 8488c90dd777e5fb7b81980b8c08ae6fcc6125c4, acre no longer installs on non Windows.

Apologies if I'm stating the obvious and this was intentional.

**Comment by PhilLast** [comment]
The expectation was that acre would be installed in versions of Dyalog earlier than 16.0 for windows only.

I'm trying to set the OLEClient unconditionally whether it's going to be used or not. This is a bug.

The ⎕Nhancements first arrived in v15.0 so Dyalog15.0 for Linux should be OK if I wasn't attempting to create the redundant _fso_.

**Comment by PhilLast** [comment]
Fixed by above commit `Acre 5.0.11+165 2019-04-05 23.40 `
