### ISSUE TITLE
Cannot install latest master branch on V17.

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#167]
```
C:\github\carlislegroup\Acre-Desktop\build.dws saved Fri Apr 12 16:26:51 2019
?     )LOAD "C:\Users\Administrator\AppData\Local\acre\acre17.0\acre.dws"
  )LOAD "C:\Users\Administrator\AppData\Local\acre\acre17.0\acre.dws"
C:\Users\Administrator\AppData\Local\acre\acre17.0\acre.dws saved Fri Apr 12 16:35:35 2019
SYNTAX ERROR
_NPARTS[8] p←(⊢,'/'~⊢/)ch FS.GetAbsolutePathName⊂p
                                                ∧
      
```

**Comment by norberturkiewicz** [comment]
It looks like a stray comment on line 1

```
 _NPARTS←{⍺←⊢
⍝     15≤⊃SV.aplver:⊢⍺ ⎕NPARTS ⍵

     ch←{('/',⍵)[('\',⍵)⍳⍵]}
     p f←'/'((-⍳⍨∘⌽)(↓__↑)⊢)((¯2×'/.'≡¯2↑⊢)↓⊢){
         {⍵↓⍨-+/∧\(⌽⍵)∊'/.'}⍣('.'=⊢/⍵)⊢⍵}ch ⍵
     f e←'.'((¯1-⍳⍨∘⌽)(↓__↑)⊢)∘⊃⍣('.'∊1↓f)⊢f''

     p←(⊢,'/'~⊢/)ch FS.GetAbsolutePathName⊂p
     p f e

```

**Comment by PhilLast** [comment]
Can you give details of the error? The commented line there is superfluous as that version of the function is supposed only to run in version 15 or earlier anyway. In versions subsequent to 14.1 the function should have been overwritten by the `setEmulators` function with the system function `⎕NPARTS` itself.

Are you doing something other than loading _...\acre\build.dws_ that was last saved as a part of Acre 5.0.4+123 on Sat Feb 09 09:23:40 2019

**Comment by PhilLast** [comment]
Sorry. Saw only email of second posting before I was assigned.

Will look further.

**Comment by PhilLast** [comment]
... second posting _after_ I was assigned.

**Comment by PhilLast** [comment]
Should be fixed with _Acre 5.0.12+173 2019-04-24 15.20_

**Comment by PhilLast** [comment]
The release notes to the above commit state that:
> ... slowing each call made to the emulators by a few milliseconds.

> Another way will be found to remove them again without disabling Install

whereas it's actually about 1.5 microseconds and mayhap they won't be.

**Comment by PhilLast** [comment]
I presume this issue arose in the attempt to install acre in Linux under Dyalog v17.

Would anyone in a position to try again close this if it now works.

**Comment by e9gille** [comment]
Just tried and got a different error in `buildWsFromSource`:
`     fns←⎕CMD'dir /s /b /a-d "',src,'"'`
won't work on on non-win platforms.
Of course, the build.dws in the root of the project hasn't changed. Remind me, how do I build the build.dws?

**Comment by e9gille** [comment]
some suggestions for non-win:

`     fns←⎕CMD'dir /s /b /a-d "',src,'"'`

can be replaced with
`     fns←⎕CMD'find ',src,' -type f'`

and
`z←⎕CMD'md "',ver,'"'`
with
`z←⎕CMD'mkdir ',ver`

note that `ver` ought to use forward slash as otherwise you end up with a single folder named `\acre\acreXX.Y` which is probably not what you want.

Also, the equivalent of LOCALAPPDATA on non-win is debatable, but this is a suggestion:

```apl
acrehome←{
     p v←2↑'.'⎕WG'APLVersion'
     w l←'WL'∊''⍴p
     s←⊃w↓'/\'
     d←s,'acre',s,'acre',v/⍨∧\2>+\v='.'
     h lad←2 ⎕NQ'.' 'GetEnvironment'('HOME' 'LOCALAPPDATA')
     w:lad,d             ⍝ windows
     ~0∊⍴h:h,d
     u←⊃~∘∊2 ⎕NQ'.' 'GetEnvironment'('LOGNAME' 'USER' 'LNAME' 'USERNAME')
     0∊⍴u:d ⍝ ? what if no user found
     l:'/home/',u,d      ⍝ linux
     '/Users/',u,'/Library/Application Support',d
 }
```

**Comment by PhilLast** [comment]
I'll issue a release of the current version tonight. The ws resulting from `buildWsFromSource` that will be included _should_ work on all platforms.

Looking back I think that was the intention all along and that `buildWsFromSource` is designed to work only on Windows so Linux &c. users will need to install from the release.

**Comment by PhilLast** [comment]
Closing this. See #169
