### ISSUE TITLE
⎕SE.acreAPI.itemname can produce a syntax error when it should not

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#168]
`⎕SE.acreAPI.itemname'abc'` creates a syntax error in case there is no open project.

**Comment by PhilLast** [comment]
I assume an empty string result and log message _"No tracked projects"_ will do?

**Comment by aplteam** [comment]
Yes!

**Comment by PhilLast** [comment]
Fixed with Acre 5.0.12+173 2019-04-24 15.20
