### ISSUE TITLE
acre.log tracks every acre call?

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#174]
The recent updates changed the way log works.  It now shows everything executed by acre.  I don't find this useful anymore.  Can I filter to only show SetChanged or function updates?

```
⊃⎕se.UCMD 'acre.log 10'
2019-05-08 10:15:53 ]Log 10                         
2019-05-08 10:15:47 ]Log 10                         
2019-05-08 10:15:41 ]Log 10                         
2019-05-08 10:15:39 ]Log 10                         
2019-05-08 10:14:56 ]Log 10                         
2019-05-08 10:14:53 ]Log 1                          
2019-05-08 10:14:40 ]Log 3                          
2019-05-08 10:14:19 Saved: #.CAS.CAS3.STATUSBAR     
2019-05-08 10:11:56 SetChanged wrote 1 file         
2019-05-08 10:11:56 ]SetChanged #.CAS.U.VersionStamp
      ⎕se.acreAPI.log 5
 2019-05-08 10:15:53 ]Log 10  2019-05-08 10:15:47 ]Log 10  2019-05-08 10:15:41 ]Log 10  2019-05-08 10:15:39 ]Log 10  2019-
      05-08 10:14:56 ]Log 10

```

**Comment by aplteam** [comment]
No doubt that this will drive Phil nuts.

I requested this because for analyzing problems one wants a log that contains traces of all calls. (That's the usual definition of a log) This was discussed on GitHub; you did not object, so there you are.

**Comment by norberturkiewicz** [comment]
I agree that log should track everything but I believe it needs (or maybe already has) a flag that can filter.  I want to know the last # unique functions I changed without all the extra data.

**Comment by norberturkiewicz** [comment]
@PhilLast are the messages categorized by type when you store them?  Maybe a category type flag or just category name along with the count?

```
[]SE.acreAPI.log 10 changed
```

**Comment by PhilLast** [comment]
As a first attempt and before seeing the above I've just changed `]SetChanged` to put _Saved: #.item.name_ in the log, which was missing, (but not the session) for each item changed.

And added another argument - `]log find`:

`      ]log find "Saved:"`, for instance, or equivalently `⎕SE.acreAPI.log 'find' 'Saved:'` would satisfy Norbert's request but maybe be more generally useful.

To be committed but not tonight.

**Comment by PhilLast** [comment]
As a last comment to this issue - I believe the request is satisfied - I'd like to add the following:

The addition of "**]acre.**_command args_ ..." to the log for each and every command is performed by the acre framework before the command code is run. A consequence is that the first entry of the response to every call to "**]acre.log all** | _n_" and potentially some to "**]acre.log find** ..."is that very command. I'm loth voluntarily to code a special case into the framework but the API function `⎕SE.acreAPI.log` bypasses the framework and so isn't itself added to the result. 

I realise that pointing this out is likely to prompt a request that all calls to **⎕SE.acreAPI**._functions_ also be added to the log but at least for now it might be more useful that this one, at least, isn't.

**Comment by norberturkiewicz** [comment]
- I would like to see command calling the command omitted from the log.
- API calls should be logged.  I'm using these quite a bit these days.

**Comment by PhilLast** [comment]
Added Bug label as commit of seven days ago - addition of "_find_" option works - only in `⎕SE.acreAPI.log 'find' ...'` and not in `]Log find ...`

Now fixed

**Comment by PhilLast** [comment]
All `⎕SE.acreAPI` function calls will now be logged similarly to `]acre.commands`.

Making an internal change of the underlying `log` function called in both protocols to start the response at the second item of each of

> **]log** _number_
> **⎕SE.acreAPI.log** _number_

in the hope that it's sufficient to overcome the perceived problem that `]log 1` merely echoes itself.
