### ISSUE TITLE
Problem with references

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#180]
I was in the process of fixing a bug in my testing framework. That is a class `Tester` that lives in `#._Tester`.

I was adding a test cases to `#._Tester.TestCases` for the bug when I realized that the documention in the `Tester` class was partly outdated, so I edited the class several times. 

Eventually I got tired of typing `##.Tester` and therefore created a ref with `T←##.Tester` and then just typed `T` with Shift+Return in order to edit the class.

Only that this made acre create a new file `Tester` in `APLSource\TestCases`, and leave the original class script alone.

Acre should work out that is is dealing with a ref, and take appropriate action. I do believe it did in the past.

**Comment by e9gille** [comment]
Isn't this the issue reported to Dyalog?
I think the question of parent space matches the scenario you are describing.

**Comment by PhilLast** [comment]
I believe so. If you edit ref __T__, that points at a script, Dyalog will fix it as the original possibly rendering the original as a ref to it. Acre will know nothing about it.

**Comment by aplteam** [comment]
I have now an experimental EXE from Dyalog were the bug is fixed. Looks good.

Since this is not - and never was - an acre issue I close this.
