### ISSUE TITLE
png icons

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#182]
I was hoping to apply one or other of the files in ***Acre\images\logo*** that are all ***.png***s to some of my folders but they are not recognised as icons by my edition of Windows 10.

If I edit with _Windows Paint_ I can probably save as some type that it _does_ recognise. If so should I leave it in ***Acre/images/logo*** where _git_ will pick it up or move it locally for my use only?

Or is there some cleverer thing I should do to make Windows recognise them?

**Comment by norberturkiewicz** [comment]
![image](https://user-images.githubusercontent.com/5807754/58818691-160d5e00-85f4-11e9-91a4-8ddeef9a6e40.png)


I tried testing myself and created a .ico form the ai file and pushed to the master.

**Comment by norberturkiewicz** [comment]
I found that setting an icon also creates a new .ini file in the project folder.  Should we add this to the master gitignore list?

![image](https://user-images.githubusercontent.com/5807754/58818928-a9df2a00-85f4-11e9-8358-21fd93f1303e.png)

**Comment by PhilLast** [comment]
Do you mean just for the acre project or something that would affect all projects?

Would it be something that acre would have to "know" about?

**Comment by norberturkiewicz** [comment]
- It would be just for the acre project folder. 
- Acre wouldn’t track anything. It’s a piece of Windows specific metadata

**Comment by norberturkiewicz** [comment]
I will test that it works on different base paths and push shortly.

**Comment by norberturkiewicz** [comment]
So this is not as trivial as originally thought.  Git does not preserve file and folder attributes that are required by Windows to properly render the desktop.ini settings.  There may be a few git hooks possible, which would execute a CMD script upon a pull or clone.  I will need to investigate this later.

**Comment by norberturkiewicz** [comment]
@PhilLast I found that two attributes must be assigned to the desktop.ini file and the repository folder itself.  Without these, the icon settings will not apply after a clone.

```bat
rem Create desktop.ini and setup folder for the acre icon.
@echo off

@echo [.ShellClassInfo] > desktop.ini
@echo IconResource=.\images\logo\acre.ico,0 >> desktop.ini
@echo [ViewState] >> desktop.ini
@echo FolderType=Generic >> desktop.ini
@echo Logo=.\images\logo\logo64.png >> desktop.ini

attrib +s .
attrib +s +h desktop.ini
```

The script above, executed from the Acre-DeskTop directory, will create the necessary desktop.ini file and set the attributes.  Unfortunately, it will be up to the user to run it.
