### ISSUE TITLE
Adding folders and code by hand

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#186]
I created a folder with no case code in a case coded project, and copied in some functions with existing case codes. Acre loaded it up fine, but gave a spurious error (I think) and left the now empty un-case-coded folder laying around:

~~~
        ]openproject c:\APLProjects\CarlisleGroup\AcreTools
Please wait - Reading 117 files from .../CarlisleGroup/AcreTools/APLSource
!!! Not fixed .aplf #.CarlisleGroup.AcreTools.UCMD
* Command Execution Failed:
~~~

I assume the empty uncase-coded folder should be deleted, and that no error message should happen.

**Comment by PaulMansour** [comment]
Subsequent actions along the same line did not produce the error, but did leave the empty folders laying around.

**Comment by e9gille** [comment]
I'm sure I've raised this before and got an explanation why the folders are left in place. I just can't remember the reason. I feel it should be possible to identify the scenario and safely remove an empty folder. Maybe it just complicates the acre code? Phil will have an answer.

**Comment by PhilLast** [comment]
The answer I think I gave was to do with the possibility advocated by Morten and Adam that source folders might contain other files not recognised by acre. 

For this reason acre filters the folder contents (`⎕NINFO`) for recognised filetypes and forgets the rest. When it renames the files the case-coded folder is created and the files appear in it leaving the old which might or might not contain other files.

I believe the recently implemented `⎕MOVE` should be capable of doing the whole thing in-situ but writing an emulator for that going back to V14.0 did not especially recommend itself while the current process works (more-or-less.)

**Comment by PhilLast** [comment]
Re. the error. Maybe there was a file being one of:
```
/APLSource/CarlisleGroup/AcreTools/UCMD-f.aplf
/APLSource/AcreTools/UCMD-f.aplf
/APLSource/UCMD-f.aplf
```
that didn't fix because there was a missing brace or del or perhaps a clash with another filetype such as `/UCMD-f.aplo`.
