### ISSUE TITLE
CreateProject does not provide any feedback on invalid call

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#187]
I accidentally executed:

```
]acre.CreateProject /path2project/myproject
```

Acre just keeps silent about the missing space. It should throw an error.

**Comment by PhilLast** [comment]
Currently shows correct syntax in Log and returns 0 or '', can't remember right now. But those syntax messages disappear in next release as no-one's looking anyway. 

If it isn't a ref to the project space it didn't work.

Moot point whether it should be an error.
