### ISSUE TITLE
Workspace Configuration File

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#188]
What follows are some ramblings. Any comments or feed back appreciated.

In a recent discussion, Gil brought up the idea again of a "workspace" configuration file of some sort, that listed all the projects you want to open, and maybe some other stuff. You could obviously have one or more of these things on your disk.  I need this sooner than later, so I am going to implement it and see what happens. One reason I need it is that after opening, say, 5 dependent projects, I need to run an initialization that sets up references between them, so even if I use the Acre Open param so that I have only one call to ]Acre.OpenProject, I still need to run something else after. 

So rather than )load to start your day,  you would do something like ]LoadWorkspace c:\...\MyWorksapce.config.

The result of this is a workspace with a set of projects loaded and initialized. ]LoadWorkspace would run []CLEAR first, to keep the analogy to a traditional workspace. Of course there could be ]CopyWorkspace as well, that does not clear. 

Issue, configuration or code? There is a thin line between a configuration file and a namespace script with a run function. The latter requires a lot less documentation and is much more flexible. The downside I guess is that you don't know what it is going to do, it could do anything. Of course, even a configuration file would probably have QuadLX expression to run on ]LoadWorkspace,  so we always are in a position that, like loading a workspace, it could do anything. But like []LX, this could be suppressed 

Thus a configuration file might look like:

~~~
[
      Projects ←'FlipDBDesktop'  'FlipDB'  'XL2APL'  
      LatentExpression←'RunThisExpression 0'
]
~~~

Alternatively we could use a generic namespace script:

~~~
:Namespace

     Run ←{
               _←⎕SE.Acre.OpenProject  'FlipDBDesktop'
               _←⎕SE.Acre.OpenProject  'FlipDB'
               _←⎕SE.Acre.OpenProject  'XL2APL'  
               _←⎕SE.AcreTools.SetupProjects '' 
                ...
               Do more stuff               ...
                0
                }

            ... could be more supporting fns defined here.

:EndNamespace
~~~

Note that this latter technique is essentially what the UCMD framework does more or less, and probably what a proper startup session framework would do - I think it would be too hard to parameterize a general startup facility, though I think Dyalog may be attempting this. 

There is no reason that both could not be useful.  The workspace config file is just a parameterized, special case version, of the general namespace script.  There may be other parameterized scripts that are useful as well.

**Comment by e9gille** [comment]
I think you said it yourself, a namespace script is "code", so by default it isn't a configuration file. The concept is similar to Morten's `.dyapp` files, which is essentially a special script with specific commands on each line *or* a trad function definition.

I feel a workspace config file should be a structured text file (JSON or similar). The valid parameters would be clearly defined and thus make it much safer to load.

**Comment by PaulMansour** [comment]
Ok, agreed.
