### ISSUE TITLE
Final Decision on format of acre.config files. (Really!)

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#189]
Ok, where are we on this? I think we last decided to support all three formats. Gil was not happy with that I think.  

It seems to me that if we support only one format, it should be APLAN or :Namespace, as we are APL programmers not JavaScript programmers. I think APLAN is better than :Namespace, as it makes it clear the file is configuration, not code., and scripted namespace is code, and can do damage. 

Note that if we have workspace configuration files, we will face the same decision. If we go JSON for acre.config, that is setting a precedent for all config files. Furthermore I believe Dyalog is working on config files too, so we should know what they are doing.

**Comment by e9gille** [comment]
>It seems to me that if we support only one format, it should be APLAN or :Namespace, as we are APL programmers not JavaScript programmers.

The fact is that JSON is not used ***only*** by JavaScript programmers. It has become a universal notation for cross language communication. This is why I (and Norbert?) feel it is more appropriate. It opens up possibilities to process the config files in other tools that don't speak APL. I failed to come up with a concrete example which is why I haven't pushed it hard, but my gut tells me it is better to use that than an APL specific notation.

Here's an article about some formats to consider: https://www.zionandzion.com/json-vs-xml-vs-toml-vs-cson-vs-yaml/

The summary is that YAML is the next generation JSON and has growing support in other languages.

**Comment by norberturkiewicz** [comment]
@e9gille My current best example for JSON was using a PowerShell script to download all git repositories found in the "Open" value of the config file.   I have also become quite familiar with YAML and OpenAPI and I regularly switch between the two looking at API specs.

**Comment by PaulMansour** [comment]
Are we going to need []YAML? It seems like by the time we get []SOMETHING, that SOMETHING is obsolete! 

Ok, given that JSON appears to be valid YAML, perhaps we should use JSON for now? 

I can be convinced I guess.

**Comment by e9gille** [comment]
>It seems like by the time we get []SOMETHING, that SOMETHING is obsolete!

My thoughts exactly, which is why I'm also happy to go with JSON.

I should add that I prefer that the config files have a standard name and use the appropriate extension to indicate the content, ie. `acre-config.json`, or `acre-config.yaml`. This ensures that we can do a smooth transition to another format when the time comes and that the files are recognised correctly by other tools.

**Comment by PaulMansour** [comment]
I was just going to ask about extensions. 

I was going to suggest that we use MyName.Workspace for workspace configuration files.

So lets say we use .json for workspace config files as well. These cannot have a generic name like acre-config, as there will be more than one in a folder possibly. So do we have FlipDB.json as  a workspace config file, loading all my projects? Do we just live with the fact that the file extension does not really tell us that is a workspace config file?  Or do we have FlipDB_Workspace.json? (I don't really like the latter).

**Comment by e9gille** [comment]
OK, now you are reaching the limits of what I have reasoned out so far. I hit the same question and didn't have a clear answer.

In general I think the extension should clearly indicate the format, but then we agree that the `.apl*` extensions add value even if a single `.apl` would have sufficed.

I don't know... 
```
FlipDB-aplws.json
FlipDB.aplws.json
FlipDB.aplws
```

**Comment by aplteam** [comment]
flipdb-aplws.json

**Comment by PhilLast** [comment]
Didn't see this issue 'til this morning for some reason. I _almost_ repeated the gist of my previous replies on this subject regarding flexibility, native _APL_ speakers, working alone and-so-on.

But _Gil_ and _Norbert's_ case regarding interoperability is sound albeit that Norbert seems already to have solved the problem.

Although I still think, given the ease of differentiation - first character "{" or ":" or "[" - that someone in the later categories above should not be forced to learn _JSON_, it would be easy to change the default file written by _CreateProject_ to be _JSON_ but to continue to support all three.

Bear in mind that _Dyalog 14.0_ does not support _JSON_ so continued use of that version would preclude not only the changing of an existing config to _JSON_ but the creation of a new project or indeed the opening of a new project created elsewhere.

Before posting this I have already made the change to _CreateProject_ in the hope that it will settle the issue 'though it wasn't as straightforward as I'd hoped. Shame that writing _JSON_ is more complicated and verbose with _⎕JSON_ than with _7160⌶_. but with no more functionality.

I haven't changed the filename as no decision appears to have been made.

**Comment by PaulMansour** [comment]
Let's do as Phil suggests here. Make JSON the default, continue to support all three. We can even drop the documentation that we support all 3, and leave it as a hidden feature, in case anyone feels that strongly.
