### ISSUE TITLE
SYNTAX ERROR: UT.nt on write

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#195]
SYNTAX ERROR
nt[1] ∪⍵{⊃∇/⍺.(⍺{(0,⍵)/⍨0,(⍺≠⍵)∧⍺=⍵.##}⍎⍕'⍺',⌽↓⎕NL 9.1),⊂⍵,⍺}⍬
                ∧

**Comment by PhilLast** [comment]
Can you give more details as to where this was called. It returns a list of all the namespaces in the tree below its argument and I haven't known it to go wrong so long as the argument is one.

**Comment by PhilLast** [comment]
The editor callback and the user-cmds/api-fns:

- CreateProject
- Erase
- OpenProject
- Redo
- Refresh
- Restore
- SetChanged
- Sourcefile
- Stats
- Undo

all call UT.nt or another function that does.

Until I can isolate which call is the culprit I can't do anything to avoid the problem's re-occurring.

**Comment by PhilLast** [comment]
Closing this awaiting a repro
