### ISSUE TITLE
File Naming Discussion

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#20]
Please see the wiki page named "Item Name and File Names".

**Comment by PaulMansour** [comment]
I think it is important that there is a way to completely avoid the naming scheme, on a project by project by project basis, if desired. Obviously there are risks and restrictions that apply. I called this a "caseless" project, but I don't think that is a good name.

If we implement this, what is a better name? I think there should be a property in the acreconfig.txt file that says 

~~~
      SomeProperty : 1
~~~

This word needs to convey the idea that duplicate names and case preservation are not an issue, i.e. working only on linux, or that "duplicate" names are simply not allowed, and that case preservation is somewhat left to the mercy of the operating system.

**Comment by PhilLast** [comment]
A consequence.
CreateProject will name text-files from any pre-existing code according to the default setting. Changing it will entail renaming all of them. If published the project will be open to its being changed by any other user.

Thus far configuration settings have no effect on the project content. Only what happens on opening it.

**Comment by norberturkiewicz** [comment]
Ultimately I'm torn on  the latest encoding proposal.   Using a single character for prefixing an uppercase is simple and easily understood.  It's ugly but there nothing more to know and there are no name length issues with encoding the letters with integers.

I don't have a better proposal but that one doesn't necessarily make it seem better for me.

Can we have both?  We already have !@.  Maybe get rid of two characters and have only one and make it a selectable scheme in the project setup file?

"UppercaesEncodingChar": "@"

**Comment by PaulMansour** [comment]
Phil, regarding changing a project from one mode to another, I wouldn't allow it.  I would force the user to _load_ the project and create a new one.

On the other hand, if project was changed from "caseless" to normal mode (ie , using case codes), then the normal rules on renaming files could be applied. That is, nothing special needs to done. And if switched the other way around, the normal rules on naming would splill out a tone of serious warning messages in the session.... so rather than manually change things the user would be better of loading and creating a new project.

**Comment by PaulMansour** [comment]
I want to reiterate here, for the record, that the case-code scheme has many benefits:

0. It is bullet proof with respect to case-preservation.

1. There is NO name mangling.  (ok, there is some mangling, but it is disguised and fully separated from the main name, in what appears to be an extension. This is no small thing.)

2. Everything will sort properly in the operating system.

3. There is no need to know ANYTHING about the encoding scheme.

4. It reduces cleanly if you work with no duplicate names, or on an operating system that is case-sensitive. You simply remove the case-code.

What are the downsides? The case code can be many digits for really long names. What else?

**Comment by PhilLast** [comment]
Re.your previous post. The point is that, whatever the default - with or without case-codes - then that is how all projects would be created, along with the files for any pre-existing code in the ProjectSpace, because the config file wouldn't exist to tell acre to change it prior to that.

**Comment by PaulMansour** [comment]
Sorry, I was not clear. I envision that there would be a third, optional flag input to CreateProject:

`       ]CreateProject c:\myproject #.MyProject 1`

to tell Acre Desktop to create a caseless project.

**Comment by PhilLast** [comment]
Understood..

**Comment by PhilLast** [comment]
Maybe not fully thought through but in terms of the word for _not_ having case codes, how about we don't have such a word. We have the term **_case code_** which I rather like so how about
]CreateProject _folder space_ 1 ⍝ is the default and therefore equivalent to
]CreateProject _folder space_    ⍝ so to turn it _off_ we do initially
]CreateProject _folder space_ 0
and the property in the config file is
CaseCode←1 ⍝ or 0 or perhaps it should be '_on_' or '_off_'

**Comment by PaulMansour** [comment]
Phil, good idea - gets rid of a very awkward attempt to name something!

In the documentation, I just document the CaseCode property, no need for any name other than CaseCode. 

I like it.

**Comment by e9gille** [comment]
May I ask if the wiki you refer to is something I have access to?

I have never tried, but I know git has a configuration setting to ignore case (which defaults to true on windows). Needless to say, it will cause issues if you try downloading/cloning a repository not meant for windows. 

If you do create a project where CaseCode is set to 0, will you also throw an error/warning if on windows and a "duplicate" name is introduced?

**Comment by PhilLast** [comment]
If you have access there'll be a link at the top of this page.

In the ws you mean? So I have #.alpha.bravo and create #.alpha.Bravo?
Have to. It would have to be on leaving the editor because the files are written immediately otherwise the definition of the second would overwrite the first.

**Comment by PhilLast** [comment]
Off topic but git seems to be 14 seconds behind me. I see the message 

> PhilLast commented 14 seconds from now

 above my last message.

**Comment by e9gille** [comment]
Thanks Phil, the mobile view doesn't include the link to the wiki. Found it now.

**Comment by e9gille** [comment]
The proposal for new case encoding looks like what I did in GAP. I chose to use hex instead of decimal numbers to get around the issue of long file names.
I like the simple approach of !@ but the advantages you list I think outweigh the disadvantages.

**Comment by aplteam** [comment]
Indeed Phil's solution is without any doubt superior. In particular the
sorting issue is nasty.

And why not use hex indeed!

**Comment by PhilLast** [comment]
Pointed out in email this am that using `10⊥10|⎕D⍳` is safer and quicker than ⍎ and simpler than messing about with ⎕VFI to pull out the value of the case code.. Slightly more time to do:
`16⊥16|(⎕D,'ABCDEF',⎕D,'abcdef')⍳` but not a lot. ⎕D doesn't itself have any case issues. Ratio is 16⍟10, about 5:6

**Comment by PaulMansour** [comment]
While there are no doubt long names that end with uppercase letters, it is much more likely that long names will be pascal cased. If we rotate the boolean flag marking the caps, we will get much smaller numbers in general I think:

~~~
      {2⊥⍵≠819⌶⍵} 'ProcessorOptimizer'      
131328
      {2⊥⌽⍵≠819⌶⍵} 'ProcessorOptimizer'      
513
~~~
I think this is Adams idea. A bonus is that all names that have one upper case letter in the first position get the case code 1:

~~~
      {2⊥⌽⍵≠819⌶⍵}¨'Paul' 'Phil' 'Norbert'       
1 1 1
~~~
 
I don't think introducing hex is worth it.  I think a string of digits is much more visually separated from the main name than a mixed string of hex chars.

**Comment by PaulMansour** [comment]
Adam has also pointed out to me that Windows disallows the following file names:

   CON
    PRN
    AUX
    NUL
    COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9
    LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9

These are disallowed even with a extra dot. So:

` CON.7.function` 

is an illegal name.

He has suggested using a dash instead of the dot:

`CON-7.function`

I prefer the dot over the dash visually, but either we use the dash or we disallow the above names.

**Comment by PhilLast** [comment]
What an incredibly stupid thing to do! How incompetent does that make them seem?

Seems it's only as the first dot separated node which is probably why we never encountered any of them with changefiles all of which start with '#.' Unless we were just very lucky.

**Comment by e9gille** [comment]
The reason I went with hex is that each character then represents 4 characters of the name and can easily be decoded. Using a single decimal number you are restricted by the precision of floating point numbers (53 bits). Admittedly, I would hope not to come across names that long (I think I have already @aplteam ), but then you would need to document that as a limitation.

**Comment by PaulMansour** [comment]
Are we talking about the hexadecimal representation of the decimal number resulting from a base 2 encode of the boolean vector marking the uppercase letters (BV) , or a base 16 encoding of BV - those are different things, right?  Can you give a few explicit examples of what you mean? Was everybody talking about the same thing when hex was mentioned?

**Comment by PaulMansour** [comment]
What if we went with hex on a reversed the boolean? Then we get names that look like:
~~~ 
Compute-1.function
ComputeBalance-81.function
ComputeNonperformingBalance-100081.function 
HTMLtoJSON-3cf.function 
alllowercase.0.function
ALLUPPERCASE.fff.function
~~~ 


The file names then look like

~~~
Compute-1.function

**Comment by PhilLast** [comment]
Actually they are the same thing but taking it in fours, using the 
actual numbers rather than APL we do

>       '0123456789ABCDEF'[2⊥⍉7 4⍴⌽28↑(⊢≠819⌶)'ComputeNonperformingBalance']
> 0100081

where the length of the name is 27.

This avoids the relatively huge number 67633216 being the 2⊥ of the 
entire vector compared to the larger of 15 and the rounded up shape in 
the above. As Gil says above 52 letters we start to lose it.

Of course we could lose that extra leading zero if we truncate trailing 
zeros from the original vector.

**Comment by PhilLast** [comment]
I appear to have replied to a post that has since disappeared.

**Comment by PaulMansour** [comment]
Thanks, Phil, I (somewhat) realized the answer to my question right after I posted it, and then deleted it. Probably bad to delete things as emails go out immediately I assume. Better to just amend the post. Will do that in the future.

**Comment by PaulMansour** [comment]
For now, we are settled on the base 16 encoding of the reverse of the boolean marking uppercase letters.
