### ISSUE TITLE
]setchanged should be able to save a new namespace and all its contents

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#202]
I..e

#.ABC.A.[]CY 'file.dws'
]setchanged #.ABC.A -r

**Comment by PhilLast** [comment]
Syntax analogous to ]erase

`]erase #.project.space -recursive`

that erases the entire space and contents we could have:

`]setchanged #.project.space -recursive`

to add all appropriate items to the project that contains the space.

OK?

**Comment by PhilLast** [comment]
Apologies.

Apparently this used to work as requested with the `.*` suffix but when I changed **Erase** to require the `-recursive` switch I changed the message to _"add switch '-recursive' to include space and contents"_ but failed to change the code of **SetChanged** so it's currently disabled.
