### ISSUE TITLE
System vars in subspaces for NEW projects

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#205]
When new projects are created **quadVars** must be created in any space sub space where namespace scope system vars differ from their parent. For example if ⎕IO is 1 in the root of the project, but 0 in a subspace, then quadVars must also be specified in the subspace. . This is only an issue on creating a project.

**Comment by PhilLast** [comment]
Done this in a branch "quadvars" which I've just "rebased". So I have one change that's not in "master".

It works.

Now what do I do?

**Comment by PhilLast** [comment]
Actually no uncommitted "changes".
Just one "commit".

**Comment by PaulMansour** [comment]
Now you want to merge to the master. This should be a fast-forward merge, which means that no conflict is possible.

**Comment by PaulMansour** [comment]
While on the master branch do from git command line:

~~~
merge --ff-only quadvars
~~~
