### ISSUE TITLE
Duplicate Folder Names

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#206]
Acre does not warn that same-name-different-case folder names exists when creating with casecode=off, and misbehaves by merging the contents!

**Comment by PhilLast** [comment]
Without considering all of the consequences I've implemented this by reporting and refusing to write any of the duplicate folders or items. But only in _case-agnostic_ OSs. (windows &c.)

No problem is sought, reported or averted if `CreateProject` is being run in a _case-sensitive_ OS determined by the _absence_ of either of **/**_project_**/aplsource/** and **/**_project_**/APLSOURCE/** after **/**_project_**/APLSource/** has been created.

It might be better if the checks were done willy-nilly, the potential problem reported in either case but only averted for _case-agnostic_ OSs.

The reporting in the _case-sensitive_ OS would warn of the problem were the project to be copied or cloned (is that the right word?) into a _case-agnostic_ OS, naming the offending folders and items.

I suspect acre would be incapable of recognising the problem after the fact as the folders would already have been merged and the files overwritten before acre got hold of them.
