### ISSUE TITLE
Should acre include a BuildWs command?

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#208]
Something like

**]BuildWs** _nspath_ **-wsid=**_'wsid'_ **-quadlx=**_'quadlx'_ **-reopen=**_'on'|'off'_

or

**⎕SE.acre.BuildWs** _nspath_ **('wsid'** _'wsid'_ **) ('quadlx'** _'quadlx'_ **)('reopen'** _'on'|'off'_ **)**

Not greatly dissimilar to what it does already for its own installation ws.

about five lines of new code.

**Comment by PaulMansour** [comment]
Yes, but not without fully ironing out dependencies, versions, reference injection, in short everything to do with package management.

**Comment by PhilLast** [comment]
Closing this pro tem
