### ISSUE TITLE
Erase confirmation

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#209]
Kai (@aplteam ) has pointed out the following by email:

> I have an ordinary namespace #.APLGUI.Markdown2Help  that I want to delete.
> When I enter
>
> ]acre.erase #.APLGUI.Markdown2Help -recursive
>
> acre reports nothing to the session, and content of the namespace is not deleted.
>
> Am I missing something?

In fact Kai was missing the log which contained the request for confirmation that always accompanies an Erase request that exceeds fifty individual items.

My reply to him includes:

This is misleading and needs to be changed somehow.

* We could lose the confirmation as the "-recursive" flag does rather indicate that the user knows what he is doing. 
* We could just lose it in the recursive case or we could lose it entirely.
* The only other way it could be necessary is if fifty or more names are supplied. This sounds unlikely but can be achieved by supplying such a list to ⎕SE.acre.Erase or catenating to ⎕SE.UCMD 'Erase ',
* Again it indicates a level of understanding that pre-empts the need for confirmation.

***I suggest losing the confirmation entirely.***

**Comment by aplteam** [comment]
I support this for all the -recursive cases. Are there other places were a confirmation is required? If so the confirmation request should go to the session rather than the log.

**Comment by PhilLast** [comment]
For `Erase` confirmation kicks in whenever fifty or more ***items*** are to be erased computed _after_ the resolution of namespaces.
Currently there are no other commands/functions that require it.
But you raise a good point. The messages should be in the session if anywhere.

**Comment by PhilLast** [comment]
Confirmation is no longer demanded anywhere in acre.

***]acre.Erase*** and ***⎕SE.acre.Erase*** require ***`-recursive`*** or ***`('recursive'1)`*** for ns contents however many.
