### ISSUE TITLE
acre's printing its version number to the session

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#216]
In case acre is not in `⎕SE` yet, it is loaded when the first acre user command issued.

When loaded something like this is printed to the session:

```
 Acre  7.0.0+293  2020-01-13  17:51
```

That does not look right in case of, for example:

```
      ]Aftersave
 Acre  7.0.0+293  2020-01-13  17:51
```

This might (again) be a good reason for having a user command "]acre.Load" because that could and should print such a message to the session, except when a `-quit` is provided, because there are corcumstances when one don't want that to happen even then.

**Comment by PhilLast** [comment]
The version has been issued as a message as a part of the setup for quite a while but only to the log. 

I sent it to the session as a part of an experiment and forgot to remove it. Sorry. I'll remove it forthwith.

**Comment by PhilLast** [comment]
Done.
