### ISSUE TITLE
]SetChanged -recursive does not always work

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#219]
It's possibly only working on the first level.

I have amended test case "Test_SetChanged_005` so that ot highlights the problem

**Comment by PhilLast** [comment]
__SetChanged 005__ now creates nss _Sub1_ and _Sub2_. Items are added to _Sub2_ but _Sub1_ is the object of the call to __Setchanged__ which adds nothing there being nothing to add.
```
2020-02-20 12:33:08 SetChanged wrote 0 files
2020-02-20 12:33:08 ]acre.SetChanged #.Test_SetChanged_005.Sub1  -recursive=1
```

**Comment by PhilLast** [comment]
> ]SetChanged -recursive does not always work

Under what circumstances does it not work? Those modelled in _Test_SetChanged_005_ do not demonstrate the problem.

**Comment by aplteam** [comment]
I cannot reproduce it anymore...
