### ISSUE TITLE
Notes in DFNS use .array Extension

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#22]
The notes in the DFNS workspace are written out as .array.   They are stored in the ws as simple strings with linefeeds (UCS 10's).

Since they are not stored as vectors of character vectors, I realize they cannot be written to .charlist.

Obviously these are candidates to be nice and readable in a text file, but they currently are not. 

Should we have a .text extension or some similar name? Or Should we just encourage vectors of vectors?

**Comment by PhilLast** [comment]
When I proposed _:Array_, I made three additional suggestions: _:Textlist_, _:Textmat_ and _:Textstring_.
Adding _.charstring_ requires minor changes to two or three cloned lines of code and the addition of an identifier to another three or four.

While we don't want to have separate types for every possible categorisation of arrays, fns &c. I think this one addition would make life a lot simpler for a number of users (assuming there are any.) And **)ED/⎕ED** supports them.

By-the-way, it's quite difficult to maintain arrays such as DRC.ErrorTable that contain a mix of numbers and charstrings. Using APLAN, it's possible to write a general array editor in one line. Two if it then invokes the same code that writes away changes made in **)ED/⎕ED**.

There is already a user command ]Array.Edit that invokes Dave Liebtag's editor. It's very comprehensive. Hooking into it might be difficult.
