### ISSUE TITLE
acre's "StartUp" parameter

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#225]
I had a hard time today because a function that acre was supposed to execute crashed because I changed something in the environment that affected the function. Because I did not change the function itself it was not exactly obvious what went wrong.

The problem is that when such a function crashes acre keeps that to itself: it's not even mentioned in the log.

Wouldn't it be better to report the crash at least in the log? I would vote for printing to the session here.

**Comment by PhilLast** [comment]
It was taken out of the session when almost everything else was. But it's always been in the log.

Here is my session
```
      ]openproject dfns
Please wait - Reading 276 files from .../acreProjects/dfns
#.dfns
      ]toaplan dfns.AcreConfig
[                                                                  
   CaseCode←'Off'                                                  
   Dependencies←''                                                 
   KeepHistory←'Off'                                               
   ProjectFolder←'C:/Users/phill/Desktop/Dyalog/acreProjects/dfns/'
   ProjectSpace←'#.dfns'                                           
   StartUp←'f00 0'                                                 
]                                                                  
```
and here is my log (newest first)
```
2020-05-19 12:39:37 ]acre.ToAPLAN dfns.AcreConfig
2020-05-19 12:39:32 .------------------------------------.
2020-05-19 12:39:32 |!!! Trapped error in Startup - f00 0|
2020-05-19 12:39:32 '------------------------------------'
2020-05-19 12:39:32 Please wait - Reading 276 files from .../acreProjects/dfns
2020-05-19 12:39:32 Opening from .../Dyalog/acreProjects/dfns to #.dfns
2020-05-19 12:39:32 ]acre.OpenProject dfns  -dependencies=on  -track=on
```

**Comment by aplteam** [comment]
Okay, now I see it in the Log as well, and that is good enough.

The problem is that I did not see it in the log earlier.

**Comment by aplteam** [comment]
I tried everything I could think of, I cannot reproduce it.
