### ISSUE TITLE
PurgeHistory

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#23]
The PurgeHistory command displays as follows in the session:

~~~
            ]aCRE.purgehistory #.FlipDB
      Opening  from c:/APLProjects/FlipDB/
       into #.FlipDB
      Creating Code folder
      #.FlipDB
~~~

I understand that under the covers it is deleting the .acre folder and then re-opening the project, but that is an implementation detail, and the message is rather confusing. I think it should just say some thing like "Local history purged". 

Things are so fast right now,  or so it appears to me, that we might not even need the code file in the future, and all purge history would do is delete the change files....

**Comment by aplteam** [comment]
I agree, if only to see whether Paul gets a notification on this.

**Comment by aplteam** [comment]
We need the code file however.

**Comment by PaulMansour** [comment]
Yes, I got an email notification!

**Comment by PhilLast** [comment]
> I think it should just say some thing like "Local history purged"

I can do that.

I guess Kai's unexplained comment is referring to code delivery of a read-only system to users where a subset of acre would just load it.
