### ISSUE TITLE
Should .md files be recognized as charlist files?

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#239]
This might be nice as markdown files are handled nicely by github.

**Comment by PhilLast** [comment]
If I were to create file _/here/this.md_ or rename an existing _/here/this.whatever_ to _/here/this.md_ then the next _OpenProject_ would read it in as charlist _here.this_.

If there were a charlist _there.that_ in the ws then _]setchanged there.that_ would write file _/there/that.charlist_ unless there already existed a file _/there/that.md_ when _that_ would be overwritten instead.

Would that be useful?

I _think_ the special casing around _.dyalog_ files that writes back a fn, op or script as a _.dyalog_ file if one of the relevant name exists - or at least a clone thereof - _might_ be co-opted to enable this.

**Comment by PhilLast** [comment]
Apologies for the ambiguity of the last sentence. The parenthesis "_- or at least a clone thereof -_" refers to the special case, not the file.
read:
> I _think_ the special casing around _.dyalog_ files - or at least a clone thereof - that writes back a fn, op or script as a _.dyalog_ file if one of the relevant name exists, _might_ be co-opted to enable this.

**Comment by PhilLast** [comment]
@PaulMansour Your original post was a question. No-one else has answered it. Do you want me to implement the above solution?

**Comment by PaulMansour** [comment]
Yes, if there are no objections. Let me just rephrase how it will work. 

If I create a .md file on disk, Acre will read it in as a .charlist file. If I edit a charlist in the workspace, and there exists a correspondingly named .md file, Acre will write back to that file. 

I assume if there is both a .charlist and a .md with the same name, then Acre should prioritize the .charlist file.

**Comment by PhilLast** [comment]
Will do.

> then Acre should prioritize the .charlist file.

That's OK at the time of writing it out but if at the time of _OpenProject- or _Refresh_  two files exist both of which _would_ create the same named object then acre objects, reports the problem and brings neither into the ws.

**Comment by PaulMansour** [comment]
Ok, sounds good.

**Comment by PhilLast** [comment]
Commit:
Acre 8.3.0+340 2021-03-17 09:35 

Import content of .md file in APLSource as .charlist without renaming.
Changing and saving a charlist overwrites a correctly named .md file.

**Comment by norberturkiewicz** [comment]
Resolved with commit a48563a74e246ffc37a04fcf76ebfec893470fe2 and 713d353a7ebbc9279b30b4057ca0b080f572f5cc
