### ISSUE TITLE
CreateProject does not result in an Open Project

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#26]
I would have thought that CreateProject would leave me with an open project, but I am forced to explicitly open it after creating it. Any reason it shouldn't just be open on creation?

**Comment by PaulMansour** [comment]
Oddly, CreateProject with only one arg still works (I don't think it should) and if used this way, it leaves you with an open project.

**Comment by PhilLast** [comment]
I can't repro this. It works for me. With only one arg it will signal an error.

**Comment by aplteam** [comment]
I cannot repro this either. Paul, please check and close when okay in 4.0.3

**Comment by PhilLast** [comment]
To clarify, 

> "With only one arg it will signal an error"

 After I've released the change that will do it.

**Comment by PhilLast** [comment]
My apologies. Whether this was the source of the problem or not the check on which projects were open was closing a root project because I was checking that project spaces were still present and
```
      ⎕NC,'#'
¯1
```

**Comment by aplteam** [comment]
The question still remains whether `CreateProject` should also open a project. Phil?!

**Comment by PhilLast** [comment]
I don't think it was ever in question as to whether it should open it. It's just that under certain circumstanses it didn't. Now it does.

**Comment by aplteam** [comment]
Sorry, I either missed the point were this got fixed or confused myself with acre 3. Now closed.
