### ISSUE TITLE
acre 4 writing to the session

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#29]
It is possible to check whether the result of a user command is assigned to a variable (##.RIU is then 1 rather than 0). If that's the case then acre 4 should not write anything to the session but return it as a result.

That would make test cases more efficient and prevent them cluttering the session.

**Comment by PhilLast** [comment]
acre writes messages to the destination determined by optional parameter "messages" (was called "displaymethod" in acres 1-3. They are not  part of the result.
```
]acre.cmd args [ messages←'off' ]           ⍝ throws then all away
]acre.cmd args [ messages←'#.global.name' ] ⍝ collects them as a charlist - unless ...
]acre.cmd args [ messages←'#.global.name' ] ⍝ points to a function which is called with the message as argument. It is expected to return a result which is ignored.
]acre.cmd args [ messages←'on' ]            ⍝ or anything else drops them into the session
```
Optional parameters remain as set until changed again or until the end of the session.

Acre makes no attempt to determine whether or not it is being called as ]acre.cmd args or as ⎕SE.UCMD'acre.cmd args'. Nor whether its result is being assigned.

**Comment by aplteam** [comment]
Excellent!
