### ISSUE TITLE
Minimum Requirement for Project Folder?

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#3]
What is, or should be, the minimum requirement for Acre Desktop to recognize a folder to be a project folder? I would like creating a project from scratch in the opsys to be as simple as possible. 

It could be any folder whatsoever, and Acre Desktop just does its thing. If there is no APLSource sub-folder, it assumes there is simply no code to fix. The config file parameters all default, and Acre creates the .acre internals.

But it might be better to have at least one requirement, the existence of the APLSource folder, even if empty, for example. This is still trivial to create by hand.

**Comment by PhilLast** [comment]
You can open a project with just an empty APLSource/ or empty acreconfig.txt.
Acre will create the .acre/ folder with empty codefile and changes folder.
 `]openproject` /path/project
will call the project "project" and create and monitor code in #.project
If you edit and save #.project.f00 then APLsource/f00.dyalog and .acre/changes/f00.CHG will be created.

**Comment by PaulMansour** [comment]
Ok, so the minimum requirement is the existence of an APLSource folder (empty will do) OR the existence of acreconfig.txt, (empty file will do). 

Got it. That works, I tried it.  I think this is fine.  I will note it in the Wiki. 

Will close this issue.
