### ISSUE TITLE
OpenProject fails in 4.0.3

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#31]
]acre.openproject   C:\T\Acre-4\Carlisle\AcreDesktop_Testcases
 Acre  4.0.3  2018-01-16
Opening  from C:/T/Acre-4/Carlisle/AcreDesktop_Testcases/
 into #.AcreDesktop_Testcases
Creating Source folder
FILE NAME ERROR: Invalid directory name ("The system cannot find the file specified.")
folderObj[2] p t s d←0 1 2 3 ⎕NINFO⍠1⊢dir,'*'
                    ∧
      dir
C:/T/Acre-4/Carlisle/AcreDesktop_Testcases/.acre/changes/

That does not exist indeed.

**Comment by PhilLast** [comment]
I suspect you are attempting to open an acre-3 project.

**Comment by PhilLast** [comment]
In acre desktop CreateProject the ".acre/" folder is not created explicitly but only in the creation of the ".acre/changes/" folder.
⎕MKDIR help
> Any part of the path specified in Y which does not already exist will be created in  preparation of creating Y itself.

**Comment by aplteam** [comment]
I did indeed use acre 3 for this although I fail to understand how. 

Anyway, acre 4 should recognize that the user attempted to open an acre 3 project and give a warning.

**Comment by PaulMansour** [comment]
There is no installed base for Acre 3, so I would not waste time coding around it.

**Comment by PaulMansour** [comment]
not "a lot" of time.

**Comment by aplteam** [comment]
Actually it's any acre project prior to version 4!

**Comment by PhilLast** [comment]
Looking for /.acre/changes/ instead of /.acre/
Fixed
