### ISSUE TITLE
Question: How will Acre-Desktop fit in with a potential package manager?

### ISSUE THREAD

**Issue by e9gille** [the-carlisle-group/Acre-Desktop#32]
I'm just in the process of planning the SwedAPL '18 user meeting in Malmö. I've spoken to Morten and he is happy to talk about their plans for a package manager for APL. I'm sure this topic is something you all have been thinking about, but I wonder if you have thoughts on how something like that would fit in with Acre-Desktop.

If I create a project containing date utilities and name it "Dates". Would I also create a distribution version in the form of a .dws file for other developers to consume or would they have to use Acre-Desktop and open/load the source code version?

How do you envisage handling dependency issues? 
Example:
ProjectA depends on ProjectX-version1
ProjectB depends on ProjectX-version2
ProjectC depends on ProjectA and ProjectB

Should ProjectC list all its dependencies (direct and indirect)?

**Comment by PhilLast** [comment]
'fraid I was a bit lost when Norbert mention packages yesterday but re. that and your second paragraph, were you by any chance listening in to our meeting?

Re. the dependencies, it sort of does but currently to no avail because I haven't implemented that bit yet.

**Comment by PaulMansour** [comment]
Good question, and yes we have been thinking about this.  We certainly don't have all the details worked out, but I think Acre Desktop is a good foundation.

I envision that any Acre Repository (by Acre Repository I mean an Acre Project + GitHub repository) that is a tool for other programmers (APLTeamUtils, FlipDB, DFNS, Rumba, etc.) has a release on GitHub that is a compressed folder containing a minimum of a .dws file that contains at least project code.  There may be other ancillary folders and files in the compressed folder that support the app.

Thus the consuming programmer has the option of going to GitHub from time to time and downloading the release, and just copying in the namespace, treating the dws as just another resource like a dll.  Or, being more active, bringing down the repository itself.

Either way the project should know its dependencies, versions etc.  Some project workspaces might just include all the dependent projects. 

Regardless, you would have to have Acre Desktop, or something built in to the interpreters or some common tool that managed and reported on the dependencies. 

I think it is going to be a lot of fun building on Acre here.

**Comment by PaulMansour** [comment]
Regarding your specific example,  I think ProjectC only lists, only knows, its direct dependencies.  The project manager then reports that there is a conflict. 

Note that each project has its "base" location. For example, I would expect DFNS to be #.Dyalog.DFNS and Rumba to be #.CarlisleGroup.Rumba.

However, a well-written project should be relocatable.  So If FlipDB depends on DFNS, I can easily embed it under #.Carlisle.FlipDB, and not have it as an  explicit dependency.  In some cases, this might be a good tact to take.

**Comment by e9gille** [comment]
Thanks Paul, glad to hear you have it in mind. Are you thinking that the package manager will be integrated with Acre-Desktop or as a separate product?

Morten suggested we book another meeting (like the one we had about Conga) to discuss different approaches for a package manager sometime in February. I expect he'll send out an invite once he's back from travelling.

**Comment by PaulMansour** [comment]
As I see it, the package manager will be a few features of Acre Desktop.  I think it will manage the dependencies of Acre Desktop projects insofar as the dependencies are other Acre Desktop projects (and Interpreter versions).  I'm not sure if "package management" means more than that.
