### ISSUE TITLE
Desperately needed: SetChange!

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#33]
Without `SetChange` Fire cannot tell acre what it has changed.

**Comment by PhilLast** [comment]
I've suggested to Kai that we implement an alternative to the ]acre.Run command that other projects  (e.g. Fire, AcreTest, AcreServer?) can hook into to request and supply specific data from and to acre desktop.

I envisage a function in the top level space that currently contains only _code - the main code space - and _qv - a quad-variables script. Its protocols could be analogs of the different command types acre desktop currently sopports: project, item and shared. getChangeFilename, getSourceFilename and setChanged would be candidates for item functions.

It could be called as 'functionName' ⎕SE.acre._run argsToFunction - or whatever.

A better way, anyone?

**Comment by PaulMansour** [comment]
I'm fine with that.  Any reason it needs to be acre._run as opposed to just acre.run?  I know you ave _code and _qv - not sure the significance of the underbar.

I assume you could get rid of ]acre.Run?

**Comment by PaulMansour** [comment]
I also assume that the text left arg, as opposed to implementing the dozen or so functions, is to avoid cluttering up the root space with boilerplate functions?

**Comment by PhilLast** [comment]
Not at all any more. When the top level space was full of methods all of which had Capital Initials there was some point.

Run will be removed from the Command list.

With this in ⎕SE.acre it'll only be particularly inquisitive bodies who'll ever know it's there. 

Using a name means I can control it more easily. It's only an identifier and would merely point at some code that might have another name entirely.
