### ISSUE TITLE
.gitignore File

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#34]
When creating  a new Acre-Desktop project, we need to create the text file named **.gitignore**, contiining the 6 character string:

~~~
        .acre/
~~~

and place it in the root of the project folder.

**Comment by PhilLast** [comment]
OK. Can we assume there might be more of these if anyone ever uses this with another SCM?

**Comment by PaulMansour** [comment]
I don't know about other SCMs.

With respect to Git, We may have to assume in some circumstances that the file already exists and we have to append to it - more on this later - I'm just getting my feet wet with the interaction of Acre and GitHub.

**Comment by PaulMansour** [comment]
Hold off on this.... there is more to it.

**Comment by PaulMansour** [comment]
On further review, we don't need this.

**Comment by PaulMansour** [comment]
On yet further review, we DO need this!

**Comment by PhilLast** [comment]
Fixed

**Comment by PaulMansour** [comment]
Thanks!
