### ISSUE TITLE
Namespace scripts

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#36]
When a project comprehends a namespace script then `CreateProject` creates a file for every single fns/opr within that namespace script **plus** a file for the script as such.

In this case it _must not_ write the fns/opr specific text files. 

The same when a namespace scripts gets changed.

**Comment by PhilLast** [comment]
I hoped that wouldn't come back to bite again but apparently it has. I'll add it to the list.
