### ISSUE TITLE
"Startup" in acreconfig.txt is ignored.

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#37]
This acreconfig.txt has no effect:
```
:Namespace
    ...
    StartUp←'#.WORKS←1'
:EndNamespace
```
It neither creates the variable nor throws an error.

**Comment by PaulMansour** [comment]
See the new wiki page on features not yet implemented.

**Comment by aplteam** [comment]
Not  yet implemented and therefore closed

**Comment by PhilLast** [comment]
Fixed provisionally BUT: 
]openproject A might request the opening of B that might do the same for C.
C will be complete before B before A.
I can't make up my mind whether Startup should run for subsidiary projects part way through opening the project that specified them - if at all.

**Comment by PaulMansour** [comment]
My gut reaction, without deep thought is that only the top project should have its StartUp code executed, and that it should be done after all sub projects are opened. 

It should be easy enough for Project A's startup to call B's startup if it wants to.

**Comment by PhilLast** [comment]
Reason I asked is because as things stand OpenProject nor LoadProject know whether or not they are the "top" project. Easy fixed.

I'll go with that and you can assume it's done.

**Comment by PaulMansour** [comment]
Fixed
