### ISSUE TITLE
References to classes and scripts

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#39]
When a namespace `foo` contains a class `goo` and a sub namespace `foo.boo` contains a reference pointing to `goo` then `CreateProject` creates two files for the same thing.

That is clearly wrong but it is not even clear to me how that can be fixed. After all the two are the same thing.

Also, what happens when the user edits one of them?

**Comment by PhilLast** [comment]
I'm pretty sure I've done this before but when I started working on acre desktop I threw an awful lot of code away deciding it would be quicker to do it again than amend it.

I guess more than one baby went out with the bathwater.

**Comment by aplteam** [comment]
But it _**can**_ be solved because every reference, when formatted, will produce a string pointing to the damn thing. That's what I forgot about yesterday.

**Comment by PhilLast** [comment]
This and the script member problem are easy to solve but might not be in tonight's release.

**Comment by PhilLast** [comment]
Fixed both issues.
