### ISSUE TITLE
OpenProject versus LoadProject

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#40]
We could get rid of "OpenProject" by introducing a flag like 

```
]acre.LoadProject -monitor=0
```
which of course defaults to 1, or something similar like `-nomonitor` when `-no` would suffice.

**Comment by PaulMansour** [comment]
I have often wanted to suggest this, as I get confused from time to time, but I'm not sure I like the alternatives. We would have to come up with names or something new for the configuration parameters as well.

**Comment by PhilLast** [comment]
Just to point out that acre does its own parsing on the command string and nowhere uses any of these flags or modifiers. Not at all sure how they would fit in with the protocols we already have.

A remnant of the properties/options that are available in acre-3 that were specific to projects is available at a session level and at present control only output, message and result.

**Comment by aplteam** [comment]
Right. I am pretty sure that Dyalog won't be thrilled at all that you coded around their implementation of user commands, to say the very least. It also leaves you vulnerable to any significant changes to any changes in this implementation.

**Comment by PhilLast** [comment]
Dyalog never complained that I didn't use ]user commands at all until about five years ago and Dan deliberately left an option to set the "Parse" parameter to '' to make the entire command string - after the command itself - to the user's "Run" function. That's all I do. acre is a perfectly standard conforming user.

Oh yes, and I never make any changes whatsoever to any supplied code in ⎕SE which I understand some users are wont to do. _That_ would make me vulnerable to changes.

**Comment by aplteam** [comment]
The only alternative I came up with is to have 

```
Load
LoadAndMonitor
```
rather than `Open` and `Load`.

**Comment by PhilLast** [comment]
Thinking about this on the way back from London. It crossed my mind that two of the principle methods typically found in a context or file menu are _Open_ and _Edit_. Dyalog use the conventional _Open_ to mean ")LOAD" in the context of APL.

By the same token it seems to me that "LoadProject" is more akin to _Open_ and "OpenProject" to _Edit_.

But to argue against my own suggestion I had it in mind to suggest a new command "]EditArray" that would take a named array, convert it identically to the way it's done for the sourcefiles as Array, CharList, CharMat or CharString, put it up in ⎕ED, reconvert the result and Save it.

**Comment by aplteam** [comment]
I think we now agree that having both commands is the best we can do.

If anybody thinks otherwise please re-open.
