### ISSUE TITLE
We already have ReadMe.md, should ReadMe.txt be something different?

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#41]
@PhilLast acre readme.txt file should be part of the project.  Right now I don't upload it.  I think this will cause a name conflict with the default ReadMe.md for git projects.

**Comment by PaulMansour** [comment]
I think readme.txt will go away, or the info init will go someplace else, when we get Phil up to speed on GitHub, I'm going about 5 miles an hour right now, and hope to drag him along after me.

**Comment by PhilLast** [comment]
I hadn't looked. I updated it after the heads-up from Kai. I didn't 
realise you had actually written installation instructions elsewhere.

Mine can go.

**Comment by PaulMansour** [comment]
Ok, the file can go.
