### ISSUE TITLE
Opening a dependent above main project.

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#45]
Opening a dependent project ref'd in "Open" config parameter above the main project is possible and obviously shouldn't be.

Something for me to sort out tomorrow.

**Comment by PhilLast** [comment]
A fix is available but perhaps not in the most satisfactory way.
If a main project now opens a dependant project above the point in the tree at which the main project is expected to locate itself the rule is applied afterwards and the main project will not open.
A warning message will suggest to the user that the config file be amended.

**Comment by aplteam** [comment]
I think that's fine. No harm done, user is notified.

**Comment by aplteam** [comment]
@Phil: ?

**Comment by PhilLast** [comment]
Implemented some time back. Fixed.
