### ISSUE TITLE
]erase not doing anything on namespaces

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#46]
@PhilLast 

]erase #.CAS.LBQUERY.*
]erase #.CAS.LBQUERY

is not erasing anything.  Am I missing something?

]erase on a full item path works as expected.

**Comment by PaulMansour** [comment]
I think we had to give this up, or punt on it, forget exactly why.  I'm sure Phil can add it back in, only ]acre restore wont work in these items.

**Comment by PhilLast** [comment]
Actually ]acre.restore could easily be made to restore all deleted items 
within a space but that might include more than were erased the last time.

**Comment by PhilLast** [comment]
Sent this to Norbert alone by mistake.

Going by spec not implemented.

Easily done if we want it. All the utility code to put it together in a couple of lines exists.

Alternatively and pro-tem:

⎕SE.UCMD 'acre.erase',,' ','#.CAS.LBQUERY.',⍤1 #.CAS.LBQUERY.⎕NL⍳10

will erase all vars, fns, ops and scripts directly in the space but not the sub-tree if such exists.

**Comment by norberturkiewicz** [comment]
I had figured out the workaround but it was messy for 20+ namespaces.

**Comment by PhilLast** [comment]
Either of these additions would do:

 Erase←{dat←⍺    
     nms←⍵
⍝ works for items and nss spec'd by name
     its←⍵~nss←⍵/⍨UT.ns ⍵
     nms←∪its,⊃,/{UT.na ⍵,'.*'}/0,⍪nss
⍝ this works items and anything spec'd by wildcard
     its←⍵~wcd←⍵/⍨'*'∊¨⍵
     nms←∪its,⊃,/⊢∘UT.na/0,wcd
⍝ existing code
     fqn typ val←getValue nms
     (⊢⊣⎕EX)dat putChanged fqn val typ MS.EX
⍝ Phil 2018-01-25 21.26
 }

**Comment by PhilLast** [comment]
In fact if you gave either the first, the project space or the second the project space followed by '.*' it would erase everything in the project!.

**Comment by aplteam** [comment]
I would not appreciate it erasing anything without a wildcard to avoid accidents, but with a wildcard it should delete everything inside. As a result the namespace would not make an appearance after the next "Open".  @Paul: would you agree?

**Comment by PhilLast** [comment]
To make the decision easier, the code is just waiting to be decommented (or is it uncommented?) and I have just deleted the alternative `]erase #.name.space` functionality without the wildcard.

As it says elsewhere, ]restore #.name.space.* would take a bit longer but is probably just a matter of surrounding a block of code with `{ ... }¨`

@Paul  ?
