### ISSUE TITLE
[message←'on'] does not work

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#48]
I specified 
```
]Openproject "C:\...\Dfns" #.Dfns [message←'#.Global']
```
but when I tried to restore the default with
```
]Openproject "C:\...\Dfns" #.Dfns [message←'on']
```
it keeps writing to the global vars.

**Comment by PhilLast** [comment]
Please can you attempt to reproduce this?

I suspect that in the transcription from your session to this thread either you have corrected some unbalanced quotes or failed to correct the typo of `message←` to `messages←`.

**Comment by aplteam** [comment]
Mea culpa - all assignments read `messages` but the last one....
