### ISSUE TITLE
]delete on a function in a scripted namespace

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#49]
Sometimes I fail to understand how it possible to write any working piece of  software at all:

Yesterday night I worked on Fire. When I run the test cases one of them failed that exercised acre's `]erase` command. The interesting bit is that it should have failed all the time, on all versions of acre, but it didn't.

The test case creates a small project with some stuff in it. Now the interesting bit is that one object is a scripted namespace (say `Foo`)  which contains two functions (say `Hello_1` and `Hello_2`) of which one - `Hello_1` shall be deleted.

The naive approach `]erase Foo.Hello_1` does not work: although acre is creating a DEL file in the `changes` folder the script remains unchanged, meaning that despite the DEL file the function will appear again when the project is re-opened. The script in the `APLSource` folder does not change at all, so the text file and the DEL file are sort of out of sync.

One could argue that this is in line with the behaviour of `⎕EX` and `⎕FIX` which both _seem_ to work on scripted namespaces but don't. (They delete/fix but don't change the script anyway, meaning that the script and what is actually available in the workspace are out of sync. According to Dyalog this is be design) But even if that is confirmed acre _must not_ create the DEL file in the changes folder then. 

BTW, Fire is checking when it does a delete on an object. If it realizes that it's an object within a scripted namespace it modifies the scripts. I can now either call `]erase` or `putChange`.

**Comment by PhilLast** [comment]
Thanks. Need to apply the same criteria as CreatProject and merely ignore members of scripts, or at least things that purport to be. And probably elsewhere. Actually if I do that in the lowest possiblr level utility then it sould ever come back!

**Comment by PaulMansour** [comment]
Fixed.
