### ISSUE TITLE
CreateProject works with only one Argument

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#5]
CreateProject appears to work when only a project folder is specified. What exactly is the default value for the project space? It does not appear to be #. 

I think we should require two arguments.

**Comment by PhilLast** [comment]
The folder name exactly as typed. Including any dots.
`]createproject /path/my.project`
creates:
`#.my.project`
in the ws,
folder:
```
/my.project/
    APLSource/
    .acre/
        changes/
        codefile.dcf
    acreconfig.txt
```
and acreconfig.txt has:
```
:NameSpace
    ProjectName←'my.project'
    ProjectSpace←'#.my.project'
    ...
:EndNamespace
```
The folder name doesn't have to be a valid APL name, nor does the project name, but obviously the project space does.

**Comment by PaulMansour** [comment]
I'd rather not have this.  It seems somewhat onerous to document. And unless I am missing something, all it saves me is doing )ns myproject before ]acre.CreateProject.

**Comment by PhilLast** [comment]
OK, CreateProject needs both folder and space.

Correlated to this seems to be:
If we can OPEN a project with only APLSource and no acreconfig then we need something to tell us where the ProjectSpace is. At present I take it from the folder name as well as the ProjectName which we're losing.

Should OpenProject fail if ProjectSpace is not specified in either acreconfig or a second item in its argument? Further if OpenProject has target specified but no ProjectSpace in acreconfig should it add it?

**Comment by aplteam** [comment]
@PaulMansour Your thoughts on this?

**Comment by PhilLast** [comment]
Seems to work well enough from the folder name. Meanwhile acre continues to avoid writing to acreConfig.txt after its initial creation.

Closing this.
