### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#50]
I intended to create a namespace script but chose the wrong indicator for `)Ed` and ended up with a class.

I then opened it again in the editor and change it from `:Class Foo` to `:Namespace Foo`. By then I already asked myself what acre would do.

Turns out that I had two scripts in the `APLSource` folder afterwards: `Foo-1.script` and `Foo-1.class`. The contents of the `changes\` folder is consistent with this.

When I re-open the project the class wins.

I think that this behaviour is not what it should be. acre should complain - or give a warning - about the name conflict either when the type change occurs or when the project is re-opened.

**Comment by PhilLast** [comment]
You are quite correct and are re-iterating the design spec. The latter option is the one in the design. This is one of the three things I've consistently pointed out that I haven't yet implemented.

**Comment by aplteam** [comment]
Please add those to the "Features not yet implemeted" wiki page.

**Comment by PaulMansour** [comment]
Kai, do you access to edit the Wiki?

**Comment by aplteam** [comment]
Yes

**Comment by PhilLast** [comment]
Do I read the implication "Well why not add it yoursekf then?"

**Comment by aplteam** [comment]
I could and would if I knew what the other two are.

Also, while I am adding the page you might just have implemented it...

**Comment by PhilLast** [comment]
Sorry Kai, mine was a facetious observation on Paul's.

**Comment by aplteam** [comment]
;)

**Comment by aplteam** [comment]
@PhilLast Where are we on this?

**Comment by PhilLast** [comment]
We get the following messages on opening:
```
!!! Multiple source files exist for:
 #.dfns.this=.class   #.dfns.this=.script
...
Type changed:
 #.dfns.this .script>.class
```
or
```
!!! Multiple source files exist for:
 #.dfns.that=.function  #.dfns.that=.operator
...
Type changed:
 #.dfns.that .function>.operator
```
`]erase` will get rid of whichever is in the ws and `]openproject` will bring back the other. But to be more sure, erase the one you don't want in the OS.

**Comment by aplteam** [comment]
Fixed.
