### ISSUE TITLE
'putchange' vs ]SetChanged

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#55]
Acres 1-3 had the `SetChanged` method and subsequently the `]SetChanged` command. So far in Acre-Desktop this is implemented as `'putchange'`, a part of the somewhat obfuscated back-door `run` interface provided for systems such as `Fire`. 

But the ability to change - by whatever method - an "un-editable" array or an auto-generated function and to save/replace it in an acre project is quite likely to be a necessity for an ordinary user, not just a hand-shaking system.

I'm therefore proposing that we re-instate `]SetChanged` as a command.

**Comment by PaulMansour** [comment]
I concurr.

**Comment by aplteam** [comment]
Implemented and therefore closed.
