### ISSUE TITLE
RANK ERROR: Invalid text array

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#56]
RANK ERROR: Invalid text array
putSource[6] z←value{⍺ MS.HI ⎕NPUT ⍵ 1}¨path
                    ∧
```
      )si
⎕SE.acre._code.putSource[6]*
⎕SE.acre._code.putChanged[22]
⎕SE.acre._code.editFix[29]
⎕DQ
      path
┌──────────────────────────────────────────────────────────┐ 
│c:/github/acre-git/APLSource/GetCurrentBranch-409.function│
└──────────────────────────────────────────────────────────┘
      value
┌───────────────────────────────────┐
│┌─────────────────────────────────┐│
││┌───────────────────────────────┐││
│││#.Acre.AcreGIT.GetCurrentBranch│││
││└───────────────────────────────┘││
│└─────────────────────────────────┘│
└───────────────────────────────────┘


      ⍴value

      ⍴path
1
      ≢value
1
      ≢path
1

```

**Comment by PhilLast** [comment]
What were the circumstances? Was this a new item just created in the editor?

**Comment by norberturkiewicz** [comment]
I believe I was stopped in the debugger and was renaming the function to create a new one.

**Comment by PaulMansour** [comment]
I've gotten this a few times. Not exactly sure how.  I have typed the name of a non existing item, edited it, maybe changed the name, pasted in some code, hit esc to fix.

**Comment by PaulMansour** [comment]
The work around is to delete the .acre folder )off and try again.

**Comment by aplteam** [comment]
Nobody has reported this again, and without a repo...

I am going to close this.
