### ISSUE TITLE
Need way to load immediate project code only and NOT dependencies.

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#57]
I'm working on packages.  I think I need a way to load in project code but NOT any dependent project code. Is there a hook in quadSe acre run function that will do this?

**Comment by PhilLast** [comment]
Not as yet but if everyone thinks it's redundant otherwise perhaps **_this_** is the raison d'être for `LoadProject`.

In other words, and this is a question I've been meaning to ask but haven't got around to yet: Should Opening and/or Loading dependencies be restricted to OpenProject?

**Comment by PhilLast** [comment]
Notwithstanding the answer to the previous question, should we perhaps restrict `LoadProject` in any case such that:

`OpenProject` _opens_ projects specified in `Open` and _loads_ projects specified in `Load`.
`LoadProject` _loads_ projects specified in both `Open` and `Load`.

**Comment by aplteam** [comment]
@PaulMansour Paul?!
