### ISSUE TITLE
Session Options

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#58]
We now have ways to assign a callback function that gets fired every time , I think, acre displays a message in the session. What is the use case for this?

What is the fundamental distinction between a message and a result?  Is there a technical reason all the messages are not simply results?

**Comment by PhilLast** [comment]
Every command returns a result. Some commands such as OpenProject display interim informational messages. Some issue warnings while continuing to do as much as they can. e.g.
```
      ]erase dfns.alrem dfn.alvals dfns.attrib   ⍝ note the typo
No open project can handle item:
 #.dfn.alvals
 #.dfns.alrem  dfns.attrib
```
where the first two lines are warning messages and the last line tells you what was erased.

Results can be intercepted by assignment either as
```
]MyResult←AnyCommand args
]acre.Command args [result←#.MyResults]
```
The rest is explained in the wiki

When Kai started writing his auxiliary commands for his own use and subsequently FIRE that interact with acre he wanted a way to turn them off or redirect them.

**Comment by PaulMansour** [comment]
I understand turning them off. I am wondering what the use case is for a callback function to fire on each message. Does it fire on each message? At the end of the command or during? Again, what is the use case for this?

**Comment by PhilLast** [comment]
Since acre 1 all messages have gone through a function called `showMsg` that initially decided whether to dump them in the session, discard them, buffer them or send them to a gui or edit window, all decided by an internal flag. By default they've always gone to the session.

It's not a callback. It's not responding to an event. It's a utility called by everything that wants to write a message. It takes a charstring, charlist or charmat, ensures it's a charlist and if it _is_ sending it to the session it runs `{⎕←⍵}¨` on it.

**Comment by PaulMansour** [comment]
I guess my question is why is this public? I'm guessing Kai wants to write the message to a file for testing?

**Comment by PhilLast** [comment]
There are three options all to do with output. The 'messages' one _could_ be hidden. Acre uses it itself to suppress the messages from `openProject` called under `PurgeHistory`. There used to be other such places when we had about fifty methods. And yes, Kai uses it in testing and possibly in the Fire interface.

But the others are more useful with regard to large results from things such as `]changes project.item` when you can set `rows` to a screenful and capture the result in a named variable to examine at your leisure.
```
      ]acre.changes #.myproject.myitem [rows←30 ⋄ result←'#.myresult'] 
```
will return the first 30 rows to ⎕SE.UCMD, thence to the session, but put all of them into `#.myresult`.

**Comment by PaulMansour** [comment]
I do not doubt the usefulness of suppressing messages or redirecting them to a variable. I was wondering about this feature in particular:

~~~
Pass message to a function:

      ]acre.cmd args [messages←'#.myFunction' ⋄ ...
~~~

It just seemed a bit overkill, I wonder who wanted it, and what they are doing with it.  And what it adds that could not be easily accomplished capturing the results in a variable.

**Comment by PhilLast** [comment]
Don't want to make any accusations but Kai asked for it a few years ago and it was extremely easy to implement as a part of the whole. If `disp` is `#.what` then:
```
     '#'∊disp:data⊣⍎disp,(2 0 3⍳#.⎕NC disp)↓',← data'    ⍝ this line results in one of these:
⍝    data⊣#.what← data                                   ⍝ named buffer - missing
⍝    data⊣#.what,← data                                  ⍝              - existing
⍝    data⊣#.what data                                    ⍝              - function
```

**Comment by aplteam** [comment]
I remember well that I used this in the past.

However, I can achieve everything I want to achieve right now without those function calls. Whether that remains to be true tomorrow I don't know.
