### ISSUE TITLE
Knowing the Project Folder

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#59]
I was against having Acre inject the ProjectFolder into the project space on Open or Load. I was against this because if I then save the ws for distribution as  a package, the data is wrong. However, if a package is opened using OpenPackage  and not )Load , this will get overwritten and be correct.  

I now think that Opening or loading a project or a package should establish a namespace in the project that is the acreconfig.txt file, with the addition of the ProjectFolder (and perhaps other useful stuff thrown in there) .

Then, no matter where you are or what your environment is,  for example, 
~~~
             #.CarlisleGroup.FlipDB.AcreConfig.ProjectFolder
~~~
will give you the project folder.

It must then be documented that, say, AcreConfig is a reserved name in the root of a project.

**Comment by PhilLast** [comment]
If the space is _assigned_ by `CreateProject`, `OpenProject` and `LoadProject`
```
      #.CarlisleGroup.FlipDB.AcreConfig ← ⎕NS names
```
rather than _named_
```
      '#.CarlisleGroup.FlipDB.AcreConfig' ⎕NS names
```
then it'll always be present and correct no matter its folder's being moved or renamed or its being opened into a different space unless )SAVEd and )LOADed and no further effort is required to prevent acre's ever attempting to save any of its contents as a part of the project.

**Comment by PaulMansour** [comment]
I'm was not worried about Acre monitoring changes and saving them. I was worried about me using quadSave to create a dws.

**Comment by PhilLast** [comment]
Assignment being the best way to ensure acre _didn't_ monitor it, I would have to ensure that not only was it _assigned into_ the project space but that it was _created within_ it.
```
      #.Projects.Project.AcreConfig ← #.Projects.Project.⎕NS names
```
Any ref `⎕SE... ← #...` or `#... ← ⎕SE...` prevents the excution of ⎕SAVE.

**Comment by PaulMansour** [comment]
I'll probably just expunge it before []Save anyway.

**Comment by PhilLast** [comment]
Is this decided?
```
#.Project.Space.AcreConfig←[
      CaseCode←'...
      ProjectSpace←'...
      Open←'...
      Load←'...
      StartUp←'...
      ProjectFolder←'...
      ...
]
```
