### ISSUE TITLE
Acre pretends to load a (changed) script but doesn't

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#60]
It shows:

```apl
Opening  from C:/.../CompareSimple/
 into #._CompareSimple
125 items loaded  from C:/.../CompareSimple/.acre/codefile
1 update loaded  from C:/.../CompareSimple/.acre/changes/
```

There is only one objects that has been changed but that does not show at all in the resulting WS.

The problem can be reproduced by opening the attached project. The object in question is `#._CompareSimple.CompareSimple`.

**Comment by PhilLast** [comment]
"attached"?

**Comment by aplteam** [comment]
I am 100% sure I dragged it onto my comment. One more time...

[CompareSimple.zip](https://github.com/the-carlisle-group/Acre-Desktop/files/1687292/CompareSimple.zip)

**Comment by PhilLast** [comment]
Thanks.
Status Window contains
```
line(45,13) : error AC0556: include target can only be a namespace "    :Include APLTreeUtils" 
                                                                                 ^
Complete: 1 error.
line(45,13) : error AC0556: include target can only be a namespace "    :Include APLTreeUtils" 
                                                                                 ^
Complete: 1 error.
```
File: "...\CompareSimple\APLSource\CompareSimple-81.class" contains
```
  :Include APLTreeUtils
```

**Comment by PhilLast** [comment]
The bug is that acre fails to monitor that the item hasn't been fixed.

**Comment by aplteam** [comment]
Fixed.
