### ISSUE TITLE
APL Characters

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#61]
I've looked into whether GitHub allows to change the font used for code blocks.

It doesn't, but I found that one can specify the code block to be "APL" which leads to this:

```apl
R←Test_AAA_001(stopFlag batchFlag);⎕TRAP
⍝ Check whether it's the right version. ("AAA" makes sure that this runs first)
⍝ The name makes sure that this runs first.
 ⎕TRAP←(999 'C' '. ⍝ Deliberate error')(0 'N')
 ⎕IO←1  ⍝ Global

 R←∆Failed

 {}Exec']acre.projects [ messages←''#.AcreMessages'' ]'
 →PassesIf 3=⎕SE.acre.⎕NC'run'

 →PassesIf'4.0.5'≡2⊃⎕SE.acre._code.getVersion''    ⍝TODO⍝  Should be an official method

 R←∆OK
```

This is how it can be achieved:

<pre><code>```apl
    ⍝ Some APL code
```
</code></pre>

The built-in font is luckily not that bad:

```
	⌶ɫ%'⍺⍵    
_abcdefghijklmno
pqrstuvwxyz¯.⍬
0123456789⊢¥$£¢
∆ABCDEFGHIJKLMNO
PQRSTUVWXYZý·
⍙ÁÂÃÇÈÊËÌÍÎÏÐÒÓÔ
ÕÙÚÛÝþãìðòõ{€}⊣⌷
¨ÀÄÅÆ⍨ÉÑÖØÜßàáâä
åæçèéêëíîïñ[/⌿\⍀
<≤=≥>≠∨∧-+÷×?∊⍴~
↑↓⍳○*⌈⌊∇∘(⊂⊃∩∪⊥⊤
|;,⍱⍲⍒⍋⍉⌽⊖⍟⌹!⍕⍎⍫
⍪≡≢óôöø"#&´┘┐┌└
┼─├┤┴┬│@ùúû^ü`∣¶
:⍷¿¡⋄←→⍝)] §⎕⍞⍣

⍠⌺⌸⊆⍤⍥  ⍝ Non-⎕AV glyphs

      ⎕SE.aplteam.Display 2 3⍴(1 2 3) 4 'APL is nice'
┌→────────────────────────┐
↓ ┌→────┐   ┌→──────────┐ │
│ │1 2 3│ 4 │APL is nice│ │
│ └~────┘   └───────────┘ │
│ ┌→────┐   ┌→──────────┐ │
│ │1 2 3│ 4 │APL is nice│ │
│ └~────┘   └───────────┘ │
└∊────────────────────────┘
```
Except that "not match" is a disaster: `≢`. It's particularly bad when the next glyph is a zero: `≢0`.

I have written this as an issue but will close it after a week or so.

**Comment by aplteam** [comment]
The `≢` problem is browser-specific. It's okay in Edge, FireFox and Opera but plain wrong in Chrome.

**Comment by aplteam** [comment]
I've remembered vaguely that I had seen a discussion on this somewhere, with Adam being involved, so I asked him:

> Yes, you've seen it at https://bugs.chromium.org/p/chromium/issues/detail?id=620629
>
> My understanding is that the devs don't care about bug reports from mere mortals. They've "decided" that they are not at fault, so they are not at fault. Once you get big enough your falsehoods become the truth. Personally I've switched to Firefox Quantum, and I'm rarely looking back.

**Comment by aplteam** [comment]
The font cannot be changed but it does some syntax colouring.

Whether you like that or not is naturally a matter of taste.

**Comment by PhilLast** [comment]
Now if the colours could be green on black ...

**Comment by norberturkiewicz** [comment]
I think it's decided that we as mere mortals have no input on the browser development.  I'm going to close this.
