### ISSUE TITLE
FILE NAME ERORR on ]openproject

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#63]
]openproject c:\github\cas7
 Acre  4.0.6  2018-02-02
Opening  from c:/github/cas7/
 into #.CAS
10952 items loaded  from c:/github/cas7/.acre/codefile
6 updates imported  from c:/github/cas7/APLSource/
* Command Execution Failed: FILE NAME ERROR      

In the same APL session, I did the process again with udebug on and there was no error.

]udebug on
Was OFF
      ]openproject c:\github\cas7
Opening  from c:/github/cas7/
 into #.CAS
10952 items loaded  from c:/github/cas7/.acre/codefile
3 updates loaded  from c:/github/cas7/.acre/changes/
#.CAS

I restarted APL and tried again.  This time there was no error

**Comment by norberturkiewicz** [comment]
@PhilLast I can reproduce the issue with a branch I have.   I'll email you a link to the source code that reproduces the bug.

**Comment by PhilLast** [comment]
Right. Erasing the .acre/ folder forced acre to load from source. I waited for the warning message and deleted the two files. A minute or so later I got the error message.
This was the only way I could force the error. Acre has just discovered 10960 files to read and while it's doing it we erase some of them. Codefile or no codefile nothing can stop someone erasing files during a wait that long. I have an operator that places 1 second ticks in the session from another thread while timing its operand - 
```
      ]openproject "C:\Users\Phil\Desktop\CAS7"
Opening  from C:/Users/Phil/Desktop/CAS7/
 into #.CAS
Creating Code folder
!!! Multiple source files exist for:
 #.CAS.TestLibrary.UnitTests.SUTILS.CUMSORT.cumtotal=.function
 #.CAS.TestLibrary.UnitTests.SUTILS.CUMSORT.cumtotal=.operator
----+----|----+----|----+----|----+----|----+----|----+----|----+----|----+----|----
FILE NAME ERROR: Unable to open file ("The system cannot find the file specified.")
getSource[3] read←{⊃MS.HI ⎕NGET ⍵ 1}
                  ∧
```
At least we could see that something is happening.
Or maybe just issue a message that says "Please wait. Reading 10960 files."

**Comment by aplteam** [comment]
@PhilLast: any progress on this one?

**Comment by PhilLast** [comment]
If my analysis above is correct is there really any point in slowing down the opening process even further by repeatedly checking whether, after starting to open a project, the user has decided to disrupt it part way through.

**Comment by aplteam** [comment]
I agree but  "Please wait. Reading 10960 files." would be nice to have, and it avoids using a thread.

**Comment by PhilLast** [comment]
Done. Thanks. Fixed
