### ISSUE TITLE
Remove codefile from .acre folder

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#64]
I'd like to make this an official request.

The codefile should be abolished in favor of always rebuilding the workspace from APLSource.  Testing with CAS, the performance is more than adequate.

At this time, I believe, @PhilLast needs to update three places when a change is made.

- APLSource file object
- Codefile item
- change file 

That's three places that an error can occur.  Is this currently an atomic operation?  What happens if one fails?

Opening a project is also complex.

- APLSource needs to be compared with codefile
- Codefile needs to be compared with APLSource
- do change files get applied to the workspace after a codefile is loaded?

All those operations go away.

Change files can still be kept but they're purely for archival purposes.  The ]undo and ]redo operations would work on the APLSource files.  ]purge.. will do nothing more than a delete of all change files.

I still want the ability to disable .acre all together but once we remove the codefile and change files don't have any application except for history, I no longer worry about sync issues between the sources.

**Comment by PhilLast** [comment]
If we accept Norbert's proposal we will lose the ability to ]Restore an item deleted from APLSource/ for which there is no corresponding changefile. i.e. something that has not been changed since ]CreateProject or ]PurgeHistory.

Norbert points out that _git_ could do it for us. No doubt but then we wouldn't be partially disabling _git's_ repository.

Nevertheless that's the only loss. Apart from that of complexity of accumulating the values from three different sources rather than the two of the proposal.

I've re-examined the timing issue and it transpires that at least a half of the additional time of loading from source rather than codefile is because of the necessity to run _GetBuildID_ on every file in the tree.

Acre currently acquires the modified-date of each file as a bi-product of identifying them. But it doesn't trust that date differences are not spurious so runs _GetBuildID_ on those whose date has changed to ensure the file has actually changed. If the .acre/ folder has been deleted we don't know which dates have changed so we run it on all of them.

If we could deem this as unnecessary and trust a mere difference in file-date we could halve the time of loading from source and reduce it still further by _not_ then having to create the codefile which I have to point out is at least twice the size of the source tree.

No objection.

**Comment by PaulMansour** [comment]
>If we could deem this as unnecessary and trust a mere difference in file-date we could halve the time of loading from source and reduce it still further by not then having to create the codefile which I have to point out is at least twice the size of the source tree.

Once the code file is gone, and if we always load from APLSource, is not all analysis of changes and file dates irrelevant?

**Comment by PhilLast** [comment]
If we are keeping change-files, which I very much hope we are, then we need to know if something has changed in APLSource/. 

Currently we don't actually reference the codefile for this. The date and hash are both kept along with the fqn after the projectspace in file .acre/sourcereg.

Open- and LoadProject "add" new items, "update" changed ones and "delete" missing ones. All three operations rely on knowing what was there before and apply them to sourcereg and the change- & delete-files.

**Comment by norberturkiewicz** [comment]
Why do change-files need to be compared to APLSource?   If APLSource is always the last change, the change-files become nothing more than a historical archive or past changes.   Nothing to compare...

**Comment by PaulMansour** [comment]
It is my feeling that the only way something should get into the change file is via an interactive edit via the interpreter.  I don't think changes downloaded from GitHub should get into the change files, nor edits I make directly in the OS.  

If this is the case, there is no need for .acre.sourcereg either, correct?

**Comment by norberturkiewicz** [comment]
> It is my feeling that the only way something should get into the change file is via an interactive edit via the interpreter. I don't think changes downloaded from GitHub should get into the change files, nor edits I make directly in the OS.

I agree with this.  A component is added to a change file when a fix is made in the workspace.  They become purely historical.

**Comment by PhilLast** [comment]
@Norbert A change-file can't be an archive of past changes if you don't put the changes into them.
We have two sources of changes. External edit or SCM; and the acre session. I don't see that they are different in kind.

@PaulMansour I don't understand why you would feel that.
The only reson to have them is to make ]Undo, ]Redo and ]Restore possible. If you change and Push something and I Pull it it will go into a changefile. If I ]Undo it, perhaps temporarily to see what it replaced - and that _is_ the most frequent use I make of undo/redo - I can then ]Redo it to get back to your change. If I do _]changes itemname_ I can see all the changes wherever they came from. Without monitoring APLSource/ I can do neither of those things.
Why wouldn't I want to?

@norberturkiewicz  I obviously can't type as fast as eithor of you.
They _are_ purely historical. Why is what is changed externally not historical?

**Comment by norberturkiewicz** [comment]
I see acre tracking external changes as having two competing source managers when in use with Git or SVN.  I never thought about acre reporting changes I made outside of APL (until now) and didn't realize it would find them.  Maybe irrational but it brings up my sync issue fear all over again.

This would lead me to confusion.  If I make a change directly in a text file, I expect that to be the latest change.  When I see a change history reported in acre, I'm assuming I've made edits via the interpreter.

**Comment by PhilLast** [comment]
@norberturkiewicz @16.03UTC I wish I'd used that as the example instead of the Push and Pull example.
If I make alternate changes in APLSource and Dyalog session why should I only want half of them to be archived?

**Comment by PaulMansour** [comment]
> If  I ]Undo it, perhaps temporarily to see what it replaced - and that is the most frequent use I make of undo/redo - I can then ]Redo it to get back to your change. If I do ]changes itemname I can see all the changes wherever they came from. 

Noted. This is indeed useful.  I withdraw my previous comment.

Norbert, I don't think your fear of sync is warranted here. The worst that can happen is that a change file does not record a change, or records a spurious change, (perhaps because the date of the files are innaccurate).  Acre is always reading the current state from APLSource.

Am I missing something? What else can go wrong?

**Comment by PhilLast** [comment]
Can I just re-iterate that not all potential users of acre-desktop - or its _Dyalog_ replacement if ever they get that far - will either want or need to use _git_ or any other SCM. We seem to be moving in the direction of relying on _git_ to do everything outside of the APL session that acre currently does inside it where - to my mind - it seems far more convenient; disabling acre's repository and relying on an external proprietory one.

**Comment by norberturkiewicz** [comment]
> Can I just re-iterate that not all potential users of acre-desktop - or its Dyalog replacement if ever they get that far - will either want or need to use git or any other SCM. We seem to be moving in the direction of relying on git to do everything outside of the APL session that acre currently does inside it where - to my mind - it seems far more convenient; disabling acre's repository and relying on an external proprietary one.


They will conform 😈 if they want to use all the great open-source libraries we'll make available.


But in all seriousness that brings us back to having an option to disable all .acre functionality for users of external SCMs and let acre be an SCM for holdouts.

**Comment by PhilLast** [comment]
Which brings me to point out that what I'm currently working on is redesigning the `getAllCode` function that merges code from the three sources to enable it to work with only APLSource/ and .acre/changes/ or with APLSource/ alone. And the `putChanged` function that works under the editor, SetChanged, Erase, Undo/Redo and Restore to work with two sources or not at all.

**Comment by PaulMansour** [comment]
> Can I just re-iterate that not all potential....

Noted. And I agree with this.  

The idea has been, and I think we are there really, that Acre is useful with no SCM, and does not get in the way and indeed works well with and encourages using a SCM system.

I like to avoid options, and if we eliminate the code file and just do change files, I would think that no option for eliminating the changes files and the .acre folder entirely would be needed, as it should never really get in the way of anything.

I think Phil is correct that the change files should monitor the APLFolder and be comprehensive.

**Comment by norberturkiewicz** [comment]
#11 

I admit that I do use ]changes and will lose that.  @PhilLast is it within acres scope for me to have a custom hook into your fix function?  I'd like to possibly do a "cmd git commit c:\..cas" after every change.  That would give me the change incremental change history.  That does require a 'squash' before pushing to the server, which consolidates the intermediate commits.

**Comment by PaulMansour** [comment]
Phil, two things.

1. If you are currently refactoring, I would plan for the option Norbert want to completely have no .acre folder, if you are not doing so already.

2. Probably just a terminology issue, but once there is no code file, don't you just have one source of code, not two? Obviously you have meta data on the files, but all fixing is done from APLSource, correct? Unless you are doing a ]undo , etc, you don't fix from the change files on Open for any reason , correct?

**Comment by PhilLast** [comment]
I was in a hurry to get out of the door when I wrote
> Which brings me to point out that what I'm currently working on is redesigning the getAllCode function that merges code from the three sources to enable it to work with only APLSource/ and .acre/changes/ or with APLSource/ alone. And the putChanged function that works under the editor, SetChanged, Erase, Undo/Redo and Restore to work with two sources or not at all.

1. What I meant was that I'm expecting to do without the codefile entirely following this discussion and that I'm also planning for Norbert's "no .acre/" option in case it's decided to allow it.

2. You're quite correct. OpenProject would just read APLSource into the projectspace and store changes in the changefiles and deletefiles if they are in operation.

**Comment by PhilLast** [comment]
@norberturkiewicz You do mean the fix function? The one that takes the fqns, types and file contents and fixes them in the ws? I can do it but it's quite demanding - not what I mean - strict. You have to get everything right.

**Comment by norberturkiewicz** [comment]
No.   When I that escape on a function and you write it to file.  I want something else to fire off.

**Comment by PhilLast** [comment]
How about we decide a generic functioname `#.something.or.other`and if it exists I call it with the same argument that gets passed to internal `putChanged` at the moment. That way you can decide exactly what it does. Maybe the filepath below APLSource/ would be enough for you to do what you need.
`⎕NC` is fairly fast:
```
      ⎕NC ut.ts '#.something.or.other'
1.355648041µs
```

**Comment by norberturkiewicz** [comment]
@PhilLast  sounds ok to me.  I'll just have to make sure it's part of my session so it's available everywhere without loading something before the project.

**Comment by norberturkiewicz** [comment]
I just did a merge of Chalas work into the CAS7 master.  After I pulled from the Github, I got 7 change files for items she changed.  I guess that's the intended behavior.  

If more than one person changes the same function and I get their changes before a merge.  Will acre put a history item in the change file for each one?   I think we should mention in the help, that after the branches are merged, the change history may not the of the right order.

**Comment by PhilLast** [comment]
Not only the wrong order but potentially incomplete.

I don't know enough about _git_ yet. If two people push their changes to the central repository do I pull them individually or get them altogether. If separately and two people changed the same item I would have to open the project in acre between each in order for acre to notice because otherwise the second would overwrite the first. 

Quite unlikely I'd have thought. If I pull twenty lots of non-conflicting changes a single OpenProject will get the lot.

Just reread your post. I don't think I understand 
> ... and I get their changes before a merge

**Comment by aplteam** [comment]
Done in 4.1.1
