### ISSUE TITLE
Invalid Text array on fix

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#68]
DOMAIN ERROR: Invalid text array
               putSource[6] z←(,∘⊂if≡¨value){(,⍺)MS.HI ⎕NPUT ⍵ 1}¨path
                 
               (,∘⊂if≡¨value)
               #.CarlisleGroup.Rumba.Conga.QuadVars   
              ⍴ (,∘⊂if≡¨value)
               1
                path
                c:/github/rumba/APLSource/Conga-1/QuadVars-11.script 
               ⍴      path
               1
               (,∘⊂if≡¨value) MS.HI
               #.CarlisleGroup.Rumba.Conga.QuadVars     UTF-8 

 
   :Namespace QuadVars
    ⎕io←1
    ⎕ml←1
    ⎕wx←3
   :EndNamespace

**Comment by norberturkiewicz** [comment]
Deleting the .acre folder seemed to fix the issue.

**Comment by PhilLast** [comment]
Tried all sorts to make this work but next release will not even try. This is a new item and acre is attempting to produce a fallback value for ]UNDO which is a hiding to nothing.

**Comment by PhilLast** [comment]
Can no longer reproduce this so I'm assuming I've finally Fixed it.
