### ISSUE TITLE
]ACRE.LoadProject missing

### ISSUE THREAD

**Issue by e9gille** [the-carlisle-group/Acre-Desktop#7]
I just tried running this command and it seems to be missing.

**Comment by PaulMansour** [comment]
Maybe related to old installed versions. I think this may have happened to me when I put a new version in, and didn't load the acre.dws workspace once in order for QuadLX to execute what ever it does that sets up the user command stuff.  Make sure you load the ws once, and then restart APL.

**Comment by PaulMansour** [comment]
I just realized that loadproject is in fact missing, and that Phil has already noted that (to me anyway) . I assume he will implement it soon.

**Comment by PhilLast** [comment]
Very soon ...

**Comment by PaulMansour** [comment]
It done.
