### ISSUE TITLE
Translate filepath to WS path

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#71]
@PhilLast is there a way I can translate a filepath string to a workspace equivalent?

I.e. APLSource/CAS3-7/LASTFILES-1ff.function  
to
#.CAS.CAS3.LASTFILES

**Comment by PhilLast** [comment]
Internally acre switches from full-path to path-within-APLSource to ns-path-within project-space to #.fully-qualified-name.
But assuming you have the exact string above
```
file←(⍴'APLSource/')↓⊃,/2⍴⎕NPARTS path ⍝ fastest way to remove the extension
name←⊃⍬⍴'/.'decodeCaps file ⍝ accepts charlist or charstring but returns list
AcreConfig.ProjectSpace,'.',name
```
The ⎕SE.acre.run function allows fqns to be converted to filepaths with
```
paths←'sourcefile'⎕SE.acre.run fqns
```
Adding the inverse would be preferable to your relying on my not changing the internals.
```
fqns←'itemname'⎕se.acre.run paths
```
The paths would have to be strictly defined: preferably as full path but so long as we all agree it could start at ProjectFolder; start at APLSource; or be within APLSource.

**Comment by norberturkiewicz** [comment]
A new itemname method would be fine.

**Comment by PhilLast** [comment]
On further thought without at least the project folder included in the path we couldn't ascertain the project and therefore the project space. If the path started at or after `APLSource `we could only compute the name _within_ the project space.

**Comment by norberturkiewicz** [comment]
Adding the project folder path to the beginning is not a problem for me.

**Comment by PhilLast** [comment]
Done
