### ISSUE TITLE
Erase versus Restore

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#73]
Currently acre.Erase accepts more than one item but acre.Restore does not.

To me that looks illogical; they should be the same.

I also think that they should both accept a namespace as argument followed by `.*` (to avoid accident). That would make it significantly easier to erase (and restore) the contents of a namespace.

According to Phil the code for this already exists for Erase and is not too difficult for Restore.

Two things to decide.

Paul, your call.

**Comment by PhilLast** [comment]
The code mentioned above is now probably obsolete as the internals of many commands including these have been changed to allow for `KeepHistory←'Off'`.

No doubt it could still be rewritten.

But the concepts intrinsic to `]command #.namespace.path.*` and `]command #.namespace.prefix*` could be applied to all item and project commands more easily at the higher level in the calling tree. Thus
```
]Erase #.project.subspace.*
```
would automatically and usefully be applied to
```
]SetChanged #.project.imported.space.*
```
and to `]Restore`, `]PurgeHistory` &c. with changes to only the calling operators `itemMethod` and `projMethod`.
