### ISSUE TITLE
Reference in a project space pointing to acre

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#75]
I have one old application which I converted into a root project because...

1. it would be a major effort to change that.
1. they are a supported feature so they should work even if a user is not encouraged to use them.

It mostly works but acre creates a ref `AcreConfig` in `#` pointing to `⎕SE`. This prevents the WS from being saved.

Culprit is probably this:

```
∇openProject[20⎕]
     space.AcreConfig←cfg⊣cfg.ProjectFolder←dat.folder
∇
```

and

```
∇createProject[17⎕]
     space.AcreConfig←cfg ⍝ ← into project ↑ add folder
```

I am not sure at all whether that can be changed but if not we should probably document it somehow.

**Comment by aplteam** [comment]
Sorry, I confused two session windows - this is **not** a root project, it's an ordinary project yet it creates a ref `#._aplteam.AcreConfig` pointing to `⎕SE.acre._code.[Namespace]`

**Comment by PhilLast** [comment]
Thanks Kai. Yes the origin of `#.projectspace.AcreConfig` is the line
```
      }⎕NS''
```
in the function that defines the fields. Or was.
```
      }#.⎕NS''
```
