### ISSUE TITLE
]stats for all open projects

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#77]
May I suggest

]stats *

to show the information for all open projects?

**Comment by PhilLast** [comment]
All acre commands are pre-parsed and categorised according to whether or not they are specific to a single project; one or more items; or more generally to the acre environment.

Unless `Stats` goes into a category of its own it's difficult to see how to restrict such a feature from being automatically applied to other commands; ]PurgeHistory or ]Changes for instance.

But then perhaps that wouldn't be a bad thing?

**Comment by PaulMansour** [comment]
Decided not now.
