### ISSUE TITLE
CreateProject from # doesn't include fns in #

### ISSUE THREAD

**Issue by e9gille** [the-carlisle-group/Acre-Desktop#78]
I just tested creating a project from a legacy app using # as the project space. It looks like all namespaces are there, but functions in the root have not been written to file. On editing one of them it triggers correctly and creates the file.

**Comment by PhilLast** [comment]
New _all-singing-all-dancing_ function to identify valid items calls utility that doesn't recognise # as a non-scripted space.

Obviously need to call new fn under editor call-back as well!! But maybe after I've corrected it.

**Comment by PhilLast** [comment]
Fixed
