### ISSUE TITLE
CreateProject from existing dws doesn't include ⎕ML/⎕IO settings

### ISSUE THREAD

**Issue by e9gille** [the-carlisle-group/Acre-Desktop#79]
This is more of a question, but I wonder if it should be left to the developer to ensure quad vars are written to file where relevant or if acre can do it. Can it be an option?

**Comment by PaulMansour** [comment]
Right now it is left up to the developer, but that could be changed I think.

**Comment by PhilLast** [comment]
The documentation could contain advice about how to set the envirnment via a script
```
      )ed ⍟ #.project.qaz
:Namespace qaz
    ##.⎕IO←... ⍝ set in parent
    ##.⎕ML←...
    ...
:EndNamespace
```
But `CreateProject` _could_ see if there is any script in the top-level and add one with a "reserved" name if not. The user could always erase it.

**Comment by PaulMansour** [comment]
There is the issue of the project root, but in theory there could different values for all the namespaces all they way down the tree. If Acre does anything automatically, I think it should only do it for the root. Phil's suggestion seems good to me. I would prefer no additional configuration files. But it might be OK to have settings in AcreConfig.txt for quadIO, etc., if the ## ns script technique is frowned upon.

**Comment by PaulMansour** [comment]
Perhaps is would be a good idea to have Acre set the values in the config file, and leave the ## ns technique for programmers to override the settings in lower namespaces. Its an exception then, not standard practice. You would only need it if your sub namespaces deviated from the root.

**Comment by PhilLast** [comment]
CreateProject creates the project space if it doesn't already exist so it inherits from the root. In any case it can be copied from the project space and set into acreConfig,txt on creation. And then copied back on creation of the project space by "Open" and "Load". 
Other candidates? `⎕IO`, `⎕ML`, `⎕WX`, `⎕CT`, `⎕PP`?

**Comment by e9gille** [comment]
I talked to Morten about this last week when going through Link, but didn't reach a satisfactory conclusion. In a traditional ws, quad vars are inherited at the point of creation. If you subsequently change the vars for the parent space, this doesn't affect the sub-spaces. 

With acre, spaces are created when loaded, so they would inherit the vars on load. If vars are only defined in project root and that is changed it would automatically trickle through down the tree on a reload.

For an existing codebase that is turned into an acre project, each sub-space may have a different setting. At the very least this new behaviour should be mentioned in documentation (migration guide) so the developer can do something about it.

Adám suggested each quad var is treated like any other var and written to a separate file inside the ns folder. I think that would require support for array notation in the interpreter and being able to use the editor to change the quad variables like any other variables.

I think separate files would just be noisy, a single file like you do now in acre is cleaner. I would only argue that it stays in the ns folder rather than the project configuration for the simple reason that the folder should be self-describing and not rely on the acre project framework.

**Comment by PhilLast** [comment]
I'd prefer, if we're to do anything positive rather than just giving advice, to insert
```
:Namespace quadVars
    ##.⎕IO←...
    ##.⎕ML←...
    ...
:EndNamespace
```
into the project space in CreateProject if there doesn't appear to be one than any other solution I've seen.

**Comment by PhilLast** [comment]
Sorry I seem to have said that before some three days ago when I was in Cornwall.

**Comment by norberturkiewicz** [comment]
Interestingly I have now run into this and it's a problem.  The Linux interpreter doesn't seem to propagate ⎕ML and ⎕IO the same as Windows.  Code that fixes properly on Windows, doesn't run exactly the same on my Linux box.  I keep on adding QuadVars namespaces in places that never needed them.

I don't like the idea of having a QuadVar in every namespace but may need to do that to ensure proper execution on between OS's

@aplteam and @e9gille am I missing something?

**Comment by e9gille** [comment]
are you saying that the quad vars are not inherited?
I just tested manually and it seems to work as expected. Haven't tested with acre yet.

**Comment by norberturkiewicz** [comment]
Everything works and test as expected when I openproject under Windows.  However, for the first time I'm loading the CAS codebase under Linux and I had several syntax errors that were solved by adding QuadVar namespaces to set ML and IO.  This was not needed when opening under Windows.

**Comment by PhilLast** [comment]
Might this have something to do with ⎕NL ordering. Do we know if they are the same twixt windows and linux?

I've identified a coding difference from acre-3 to acre-desktop that might or might not be significant in the order of fixing stuff. I'll probably change it in any case because I think it's possible it could cause such a problem.

**Comment by PhilLast** [comment]
acre will now create each container namespace one at a time immediately prior to `⎕FIX`ing a script within it and in order of fqn length. Spaces _not_ containing scripts will then all be created before the rest of the items that will populate them. This should at least be OS independent but I'm 99% sure it's foolproof unless someone decides to try to defeat it.

Was it decided that `CreateProject` will create a qv script in each ns whose quad vars differ from its parent, just in the project space or not at all?

If at all we need to know two things:
Which vars? `]salt.snap` stores `⎕IO ⎕ML ⎕WX ⎕CT ⎕PP` and non-empty `⎕USING` for each ns in a file called `name.txt`. My feeling is that the presence of the script with just `⎕IO ⎕ML` will be sufficient in almost all cases and the user can modify it, multiply it or erase it in any case.
What name for default script? I use `_qv`. I notice many uses of `QuadVariables` or various abbreviations.

**Comment by norberturkiewicz** [comment]
I would stay away from []USING.  This should be set at startup during the app boot process.

**Comment by norberturkiewicz** [comment]
IO, ML and WX are the primary ones that come to mind.  At least the ones we use.

**Comment by PhilLast** [comment]
In 4.2.1 CreateProject will fix script
```
:Namespace quadVars
    ##.(⎕IO ⎕ML ⎕WX)←? ? ?
⍝ This script was fixed by acre
⍝ it can be kept, amended or ]erased.
:EndNamespace
```
in the project space if no item exists with that name.

**Comment by PhilLast** [comment]
Done
