### ISSUE TITLE
Why do we need ProjectName?

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#8]
As I write the documentation for the commands, I wonder why we need the formal concept of a project name. Obviously people will name their projects, and usually will name their folders and namespaces for them. But currently we do not allow two projects with the same name to be open at the same time. I think we are going to regret this, and I don't see what it accomplishes, other than complicating the documentation.

There are only two commands that currently require the project name :  ]consolidate and ]Stats. No doubt there will be more in the future. But why won't the projectspace work as a replacement? By definition, it will be unique. So there is no issue of opening /CarlisleGroup/Utilities and /APLTeam/Utilities. at the same time.  Furthermore, the projectspace actually exists so autocomplete will work in the session,  and I think user commands know your current namespace, so you can use a short name if you are already in the right spot. Thus if I am in #.CarliseGroup I can do:

`]Stats Utilities` 

or from anywhere I can do the more verbose:

`]Stats #.CarlisleGroup.Utilities`

I propose we get rid of the concept of project name.

**Comment by norberturkiewicz** [comment]
This does make sense.  Let the SCM be used to set the project/solution name since it will also be keeping track of all ancillary files. 

ACRE Desktop only cares about the project namespace.

**Comment by PhilLast** [comment]
I'm open to this and will look at code impact but Kai has already requested that I reinstate the symbolic name for opening projects without having to specify the whole path.
That might or might not impact this idea.

**Comment by PhilLast** [comment]
Would have no effect barring the case-intolerance of space vs name.
Wouldn't be difficult.
Wouldn't preclude a symbolic name for Open- and LoadProject were that ever at the top of the list.
Required changes would more easily allow suggestion to make ]changes method dual purpose and permit benefit to be applied to other project- and item-methods.
Might well reduce code volume.

Decision?

**Comment by PaulMansour** [comment]
Thanks Phil. 

Sounds like everyone is on board. Let's remove ProjectName.
