### ISSUE TITLE
Refresh Command

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#81]
We seem to have general agreement that automatic, continuous synchronisation responding to a file watcher is not what we want.

However, controlled, timely, intermediate synchronisation, whether `KeepHistory` is `'On'` or `'Off'` would be simple to achieve with a `]Refresh project` command. This would merely bring in additions and changes and expunge deletions made to the source tree since the last Open/Load/Refresh using a subset of the code that does the job for Open/Load.

The speed of Open/Load, especially subsequent calls using the machine's cache, may appear sufficient to obviate the need but if an open project has an SI stack that we want to keep for the nonce while synchronising some other part of the project after a SCM "pull" then a refresh would fit the bill apart from its being somewhat quicker.

To quell any fears in advance, with `KeepHistory 'Off'`, this would _not_ entail any additional file writes; with it `'On'` change/delete files would be written.

**Comment by PaulMansour** [comment]
Agreed: ]Refresh   #.MyProject.

**Comment by PhilLast** [comment]
Done
