### ISSUE TITLE
Closing projects

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#82]
Sometimes it's necessary to close one project before opening another because of the rule that no project may be opened inside another. The mechanics of acre's "knowing" which projects are open is complicated by "root" projects. For anything else all acre needs is whether the project space exists. For root projects "#" always exists. If we've had a root project open, we can't expunge '#'. We must instead expunge everything in it. )CLEAR does the trick but we must tell acre before we start repopulating the ws because it can only "close" the project if nothing exists when it is called.
To close a project whose space is `'#.myspace'` we only need `⎕EX '#.myspace'`
To close a project whose space is `'#'` we need
```
)CLEAR
]projects
```
To suppress the `"No open projects"` message issue the second command as `]projects [messages←'off]`

**Comment by aplteam** [comment]
In that case I vote in favour of an `]acre.CloseProject` command

**Comment by PaulMansour** [comment]
The work-around above is acceptable.
