### ISSUE TITLE
Potential conflict with project space and AcreConfig.ProjectSpace

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#83]
The namespace created by OpenProject, `project.AcreConfig`, contains the value for `ProjectSpace` as stored in `acreConfig.txt`. If a second item is given to `]openproject` to relocate the project within the ws-tree the reported space will be different from the actual. e.g if `acreConfig.txt` contains: `ProjectSpace←'#.myproject'` then normally one would expect
```
     #.myproject.AcreProject.ProjectSpace
#.myproject
```
but
```
      ]openproject ./myproject #.newspace
...
      #.newspace.AcreConfig.ProjectSpace
#.myproject
```
Should `AcreConfig.ProjectSpace` reflect the default or the present state?

**Comment by aplteam** [comment]
It's called "AcreConfig" which means that it refers to the Config file. Therefore I think it's current behaviour is fine.

Of course it could be argued that the second parameter overwrites the definition in the config file, but when the programmer has explicitly asked to put it elsewhere she would/should know that anyway. So rather asking what she had decided herself I can only imagine that she wants to know what the config file's definition is.

**Comment by PaulMansour** [comment]
Decided: The config file rules.
