### ISSUE TITLE
Future compatibility

### ISSUE THREAD

**Issue by PhilLast** [the-carlisle-group/Acre-Desktop#87]
0.
If we expect _Dyalog_ to plump for Morten's source file extensions `.apla .aplf &.c` perhaps we could include reading them as synonyms and possibly move to deprecating our own at a future date.

--------
1.
If it's at all likely that anyone would want to mix apl source files with data or any other filetype `/APLSource` becomes rather a misnomer.
```
  f01←{⍺←⊢
     p d←{⍵.(Path Date)}fileTree ⍵
     p d/⍨←⊂~(∨/'/.'⍷⊢)¨p
     x←(2⊃⎕NPARTS)¨p
     p d x/⍨←∊/Cc x MS.AZ
     {(⊣⌿⍵)/⍨∧⌿⍵=⍤1⊣⌿⍵}↑p
⍝ Phil 2018-04-09 12.13
 }
```
The above function cut, pasted and fixed into `⎕SE.acre._code` and given the path of a project folder as argument will currently return the path of its `APLSource/`. But it contains no reference to that name. What it's actually returning is the longest common prefix of all folders that contain any apl source file or folder that contains such, except folders whose name starts as `/.`.

At present the only  exception would be if a project's `APLSource/` contained only a single folder that contained the rest of the tree, that is a superfluous level immediately inside `APLSource/` and it is that extra level that would be returned.

This shows that the name `APLSource` or indeed any reserved name is redundant. If a source file were placed directly into the project folder then the project folder would be returned.

Kai points out that we can't presume that no user may wish to store apl source files out of acre's remit. The `.` prefix more-or-less precludes acre's intrusion in this respect but if desired we could include a `.acreignore` file as well.

--------------

**Comment by PhilLast** [comment]
I stick by what I've said above but obviously `CreateProject`, given pre-existing code in the ws, would have to put it somewhere so _APLSource_ as the name of a subfolder of the project would be as good a convention as any. This would then appear as a sub-namespace of the project space were it not to be renamed and if source files were placed in the project folder.

**Comment by PaulMansour** [comment]
Regarding 0:  I'm more than fine with  .apla, .aplf, .aplo, .aplc, .apli which I assume mean array, function and operator, class and interface. What's the proposal for scripted namespace? .apls?  The sooner we move over the better, as this obviously involves renaming everything, and somewhat trashing the history of a project.

**Comment by PaulMansour** [comment]
Regarding 1:  I don't really get the attraction of mixing in APL stuff. If you have a folder structure with APL stuff, the folder structure represents the ns tree. If you throw a say, dll file into one of the folders, the .dll is NOT in the ns tree. It is simply not related in any way. If APL cannot load it and put it in the namespace as an APL object, then it should not be in there.

It also precludes having items like .json files that may or may not be considered APL objects. 

Another problem is that it makes writing tools harder. How do we know where the APL code is? We must now search directories. 

I think it is a really bad idea all the way around.

**Comment by PaulMansour** [comment]
Back to 0: what is the complete proposal, including what we do now for  .string .charlist . charmat., etc.?

**Comment by PhilLast** [comment]
```
apla array
aplc class
aplf function
apli interface
aplm charmat
apln scripted-space
aplo operator
aplv charvec(?)
apl? charlist or charstring
```
He only suggested two of the char types: `aplm` and `aplv` but I wasn't sure to which of ours `aplv` equated. Perhaps he's unaware of John's predilection for char strings.

**Comment by PhilLast** [comment]
1: I agree but if we want to be compatible with the best that Dyalog come up with then acre might have to read a folder without a named "APLSource". The above function - sans bugs - will do it. What it'd do next is up for discussion.

0: Given that we are way ahead we could just go for Morten's original six including `apln` for a scripted space and add `aplm, apls & apll` for _matrix, string_ & _list_ as a _fait accompli_. I feel the latter two are better descriptions than _vector_ that could be either. We definitely need all three as we then cover everything that is currently editable in the Dyalog editor.

As to renaming, acre will start doing it soon in any case when I've implemented the rules for name/case discrepancies. If we go on reading `.function, .operator` &c. but write `.aplf, .aplo &c.` then eventually anything that gets changed will have been renamed and anything that hasn't won't matter unless the user wishes to switch to using Dyalog's own brand.
