### ISSUE TITLE
"aplcore" should be added to .gitignore

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#88]
I vote to have aplcore set in .gitignore by default.   I've tried to upload these more than once now.

**Comment by aplteam** [comment]
Make sure that they are saved elsewhere.

I have an entry "aplcorename" in my registry for every installation of Dyalog which reads:

C:\DyalogSysErrors\aplcore_Dyalog APL_W 14_1 Unicode_*

The `*` makes sure that a sequential number is added.

That comes with the benefit of aplcores not overwriting each other any more.

**Comment by e9gille** [comment]
Is that done with environment variables on non-win?

**Comment by PhilLast** [comment]
I guess there's no harm in adding it anyway. If I do is it just `aplcore` on its own or does it need decorating as in `aplcore.*` or including slashes?

**Comment by PhilLast** [comment]
I'd forgotten about this having had no answer. Will add `aplcore` as is. Can't do any harm.
