### ISSUE TITLE
project folder is not represented the same in Acre on nix.

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#89]
]projects
 #.CarlisleGroup.CASFile        /home/ec2-user/Github/CarlisleGroup/CAS7/../CASFile/
 #.CarlisleGroup.Utilities      /home/ec2-user/Github/CarlisleGroup/CAS7/../TCGUtilities/
 #.CarlisleGroup.AcreTools      /home/ec2-user/Github/CarlisleGroup/CAS7/../CAS-File-Server/../Rumba/../AcreTools/
 #.CarlisleGroup.CFS            /home/ec2-user/Github/CarlisleGroup/CAS7/../CAS-File-Server/
 #.CarlisleGroup.CASDataModels  /home/ec2-user/Github/CarlisleGroup/CAS7/../CASDataModels/
 #.CAS                          /home/ec2-user/Github/CarlisleGroup/CAS7/

There's a /../ in the folder path.

Windows does not do this.

      ]projects
 #.CarlisleGroup.CASFile        C:/GitHub/CarlisleGroup/CASFile/
 #.CarlisleGroup.Utilities      C:/GitHub/CarlisleGroup/TCGUtilities/
 #.CarlisleGroup.AcreTools      C:/GitHub/CarlisleGroup/AcreTools/
 #.CarlisleGroup.CFS            C:/GitHub/CarlisleGroup/CAS-File-Server/
 #.CarlisleGroup.CASDataModels  C:/GitHub/CarlisleGroup/CASDataModels/
 #.CAS                          C:/GitHub/CarlisleGroup/CAS7/

**Comment by PhilLast** [comment]
I obviously didn't give enough attention to the Help for **⎕NPARTS** which reads
```
File Name Parts R←{X} ⎕NPARTS Y 

Splits a file name into its constituent parts.
[...]
The optional left-argument X specifies whether or not the file name specified by Y is normalised 
before being processed. The default value 0 means no normalisation; 1 means normalise as follows:

Pathnames are made absolute. 
On Windows, all "\" directory separators are changed to "/". 
The resultant name is simplified by removing extraneous directory separators etc. On Windows, 
this includes resolving occurrences of "." and ".." within the name. On non-Windows platforms 
single "." are removed. Note that ".." and symbolic links interact differently on Windows to 
other platforms; on other platforms they cannot be removed without reference to the file system 
itself and are left in place. 
```
I introduce the `../` into paths in the dependency part of **Open-** and **LoadProject** because we decided that an unadorned name would represent a sibling project. I do not presume that the current directory is either the current project folder or its parent so I attempt to build a path that will be understood from the current project and the target. In windows this requires `currentprojectfolder,'/../',target` and **1 ⎕NPARTS** resolves this correctly. It appears that it _works_ in 'nix but doesn't attempt to change it.

**Comment by PhilLast** [comment]
I used to resolve and normalise them myself in older versions of acre but ⎕NPARTS allowed me to think I could ditch it. I don't actually see why Dyalog doesn't but it looks from your results that it should work. I'll redo it.

**Comment by PhilLast** [comment]
No but it'd be nicer if it lost the to-ing-and-fro-ing. It's no big deal to code.

**Comment by PhilLast** [comment]
Another good reason to do it is because I've always wanted to have an excuse to code a `2⍱/`!

**Comment by PhilLast** [comment]
Included in latest. Should have fixed it. Please reopen in not.
