### ISSUE TITLE
Item History Command

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#9]
I think we need:

`]Acre.History item`

that lists the source of  the local versions going back in time:

Version9
Version8
Version7
etc.

**Comment by PhilLast** [comment]
Take it you mean the contents of the .CHG file in /.acre/changes/. Would you want to be able to select?

**Comment by PaulMansour** [comment]
No need to select.  Dirt simple. Just a listing of the source code spilling into the session, with maybe dates and times if easily available. Something like:

~~~
     ]Acre.History #.FlipDB.Core.sum

Version 10,  saved  2017-12-31 at 23:59:59
{listing of source code}
Version 9, saved 2017-12-30 at 12:59:59
{Listing of source code}
...etc.
~~~

**Comment by PhilLast** [comment]
I currently have 48 versions of #.acre._code.openProject, 1518 lines in the session.

**Comment by PaulMansour** [comment]
Noted. 

How about you print a reasonable number of lines (say 50 tops), and then at the bottom, if truncated, it says

~~~
... more.
Use  -all to display all.
~~~

The flag could accept specific ints, so -3 means print out the last 3 version, -all means print everything, if no dash, then always truncate for safety,

**Comment by PaulMansour** [comment]
We could also have way to pipe to a file, or pipe to a folder with a file for each version.  No need to jump on it now, just food for thought.

**Comment by PhilLast** [comment]
Can always assign
`]z←changes #.this.thing`
then just Shit+Enter on z

**Comment by PhilLast** [comment]
sorry Shift

**Comment by PaulMansour** [comment]
That's fine.  Just truncate then, and let the user do the assignment to get everything. I assume inserting the assignment is a feature of user commands and not acre specific?

**Comment by PhilLast** [comment]
Yes UCMD parses it and no you cannot know. Other approaches are available.
