### ISSUE TITLE
Acre and Git Branches

### ISSUE THREAD

**Issue by PaulMansour** [the-carlisle-group/Acre-Desktop#90]
In my quest to design "Acre Flow" (a Git workflow for small APL teams) l have run into the following problem.

When switching branches, we must reopen the project, otherwise our workspace is out of sync with the folder structure (yes, I used the word sync, this might please Morten!). 

However, if my current namespace is the project space (or below the below the project space), which it is highly likely to be, as that is the project I am working on, then reopening the project leaves me in strange state: I am in a reference to the project space that does not exist anymore. Not good.

A workaround is this:

```
ReopenProject←{
     ⍝ ⍵ ←→ Project Folder
     _←⎕SE.UCMD']Acre.OpenProject ',⍵.AcreConfig.ProjectFolder
     _←('⎕THIS⊣⎕CS ⎕CS ''#''',⊂'ER')⎕PFKEY 5
     ⎕NQ ⎕SE'KeyPress' 'F5'
 }

```
Kai is probably laughing at me now, as if I remember correctly, he wanted to be able to do something like this (I think he wanted to keep his own vars in the project space and have it survive a re-open), and I insisted that the namespace be deleted and recreated.

A couple of questions to ponder:

1.  Should we revisit what acre does on OpenProject with respect to the project space? 

2.  Should there be an  ]Acre.Refresh command perhaps?

**Comment by aplteam** [comment]
Smiling, not laughing ;)

I can only think of me wanting to be able to create references inside the project space opening a project. For example, for a project _FilesAndDirs that depends on APLTreeUtils:

```
'_FilesAndDirs'#.⎕ns''
#._FilesAndDirs.A←#.APLTreeUtils
]acre.OpenProject C:\...\FilesAndDirs #._FilesAndDirs
```

I am still not convinced that this is not a good idea.

Anyway, I think that the idea of changing branches while APL is up and running is a no-go. If you want to switch branches then do `)OFF` (or `)Clear`), switch branch and start from scratch.

To make that as easy (or difficult, depending from the angle) as possible I would suggest to implement a user command `]git.branch` which requires at least a path pointing to the project folder; when fed with an additional argument (=branch name) it should complain in case the WS is not empty.

**Comment by PaulMansour** [comment]
Kai, I think to effectively use Git, it has to be much easier than that.  I'm developing a few commands for Git to use in the APL session (for now, just in AcreTools, eventually in a user command.) In the normal course of events, I should never need to use another tool like Git Hub desktop or SourceTree. 

I have a function called CheckOut. It simply does a git checkout,  and reopens the project.  I run the function from within the project space.

**Comment by PhilLast** [comment]
'though I suppose I should apologise for not having finished it yet. Was working on it earlier today.

**Comment by aplteam** [comment]
I for myself will always )off, check out and restart my APL session  because I am certain that if I do not stick to such a routine then one day I will bitterly regret it and curse at branching.

When at the moment of a branch switch you are in a namespace that due to deletions will become empty as a result of ]Refresh then this namespace will not disappear. So ]Refresh leaves the WS in a different state from starting with ]openproject in a CLEAR WS.

I don't even want to think what happens when I am tracing some code when issuing a branch change followed by ]refresh.
