### ISSUE TITLE
sourcefilename

### ISSUE THREAD

**Issue by aplteam** [the-carlisle-group/Acre-Desktop#92]
At the moment `sourcefile` delivers a result only (via the `run` function) when the object (fns, opr, ...) specified to the right lives in an open acre project. Understandably so because otherwise acre cannot _know_ where it lives.

However, I have tools that know the path but want to ask acre what the filename (without the path) and the extension are.

Therefore I propose that when acre is passed an object that is not part of any open acre project it returns just the filename without the path including the extension, and if the object does not even exist in the WS the extension is just `.*`.

**Comment by PhilLast** [comment]
Possible but will need special code as names are filtered for membership of projects before they reach the method.

**Comment by PhilLast** [comment]
Requirement implemented as `'casecode'⎕se.acre.run name` that adds or resolve case codes.
