### ISSUE TITLE
Existing projects fail to open with 4.3.0

### ISSUE THREAD

**Issue by norberturkiewicz** [the-carlisle-group/Acre-Desktop#95]
]openproject c:\github\carlislegroup\cas7
    Opening from c:/github/carlislegroup/AcreTools/
    to #.CarlisleGroup.AcreTools
    Please wait - Reading 58 files from c:/github/carlislegroup/AcreTools/APLSource/
    * Command Execution Failed: VALUE ERROR

    ]udebug on
Was OFF
      ]openproject c:\github\carlislegroup\cas7
Opening from c:/github/carlislegroup/AcreTools/
 to #.CarlisleGroup.AcreTools
Please wait - Reading 58 files from c:/github/carlislegroup/AcreTools/APLSource/
VALUE ERROR
openLoad[16] z←dataspaces track/dts    ⍝ keep only tracked dependants
              ∧
      track
1
      dts
 ⎕SE.acre._code.[Namespace] 
      dataSpaces
 ⎕SE.acre._code.[Namespace] ∘      ∇{⊢⍺.ids←⍺.ids{(⍺~⍵)∪⍵~⍺}⍵}        
     ∇                                                                
      track/dts
 ⎕SE.acre._code.[Namespace] 
      dataSpaces
 ⎕SE.acre._code.[Namespace] ∘      ∇{⊢⍺.ids←⍺.ids{(⍺~⍵)∪⍵~⍺}⍵}        
     ∇                                                                
VALUE ERROR
openLoad[16] z←dataspaces track/dts    ⍝ keep only tracked dependants
              ∧
VALUE ERROR
openLoad[16] z←dataspaces track/dts    ⍝ keep only tracked dependants
              ∧
VALUE ERROR

**Comment by PhilLast** [comment]
Sorry, fixed this in built system but forgot to reproduce change after rollback so committed and pushed previous version. Only affects dependants. Fixed, committed and pushed.
